/**
 * SERVER-ONLY. Generic, on-demand, cross-user content library — the reusable
 * generalization of the Listening shared-story mechanism
 * (listening_shared_stories + acquire_or_get_listening_shared_story), applied to
 * Pronunciation and Writing.
 *
 * INVARIANT (never violated here): the flow is always synchronous and on-demand
 *   request -> acquire compatible item the user has NOT seen
 *          -> ready:  reuse (no AI/TTS call)
 *          -> miss:   generate NOW (caller callback) -> persist -> serve
 * There is NO cron, worker, queue, prefetch or warm-up: the library is populated
 * organically by real requests, and a dead generation lock is reclaimed by the
 * NEXT request (lock_expires_at), never by a background routine.
 *
 * This module owns ONLY the shared cache lifecycle (acquire / persist / audio /
 * per-user usage ledger). The actual AI text generation and Azure TTS stay in
 * the CALLER's callbacks so their existing AI-Gateway wrapping, metering and
 * error taxonomy are preserved unchanged (§11). Per-user quota, scores,
 * responses and curricular credit remain in the caller's own per-user tables —
 * this library never touches them.
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import { recordServerTiming } from '../_debug-log';

// Long enough to cover a realistic OpenAI (+ Azure TTS) run with margin; short
// enough that a genuinely crashed request doesn't block a slot for long before
// the next request can reclaim it. No cron reaps it — the RPC re-checks
// lock_expires_at itself. Mirrors SHARED_STORY_LOCK_DURATION_SECONDS.
export const SHARED_CONTENT_LOCK_SECONDS = 180;
export const SHARED_CONTENT_AUDIO_LOCK_SECONDS = 120;

// Dedicated private bucket (NOT 'listening-audio', which the listening:* audit /
// cleanup scripts scan). One file per item, deterministic path.
export const SHARED_CONTENT_AUDIO_BUCKET = 'shared-content-audio';

export type SharedContentModality = 'pronunciation' | 'writing';

/**
 * The pedagogical-compatibility identity of a shared item. Every field is a real
 * curricular attribute (multilingual-ready); two items are interchangeable only
 * when ALL of these match. `curriculumVersionId`+`subtopicKey` pin the recorte
 * (and therefore the level); `templateKey`+`promptVersion` pin the generator so a
 * prompt edit never silently reuses content produced by the previous prompt.
 */
export interface SharedContentIdentity {
  modality: SharedContentModality;
  learningLanguage: string;
  interfaceLanguage: string;
  curriculumVersionId: string | null;
  subtopicKey: string;
  levelCode: string;
  exerciseType: string;
  templateKey: string;
  promptVersion: number;
}

export interface SynthesizedAudio {
  audio: Buffer;
  mimeType: string;
}

/**
 * Optional audio capability. When present (Pronunciation), a reference TTS is
 * persisted alongside the text and reused; when absent (Writing), the item has
 * no audio. Audio is BEST-EFFORT and independent from text readiness: a failed
 * TTS never blocks text reuse and never yields a broken audio pointer (§9).
 */
export interface SharedContentAudioSpec<TContent> {
  /** Extract the text to synthesize from the (already-ready) content. */
  extractText: (content: TContent) => string;
  /** The Azure voice + locale the reference audio is generated with (traceable). */
  voice: string;
  locale: string;
  /** Synthesize the reference audio. Throwing is fine — audio degrades gracefully. */
  synth: (text: string) => Promise<SynthesizedAudio>;
}

export interface SharedContentAudioResult {
  base64: string;
  mimeType: string;
  voice: string | null;
  locale: string | null;
}

export interface GetOrCreateSharedContentOptions<TContent> {
  /** Service-role client (writes are backend-only; RLS is honoured, not bypassed by app users). */
  client: SupabaseClient;
  userId: string;
  identity: SharedContentIdentity;
  /** Model id recorded for traceability (never part of the reuse identity). */
  generatorModel?: string | null;
  /** Generate fresh, validated content on a cache miss. Runs ONLY when this request must generate. */
  generateContent: () => Promise<TContent>;
  audio?: SharedContentAudioSpec<TContent>;
  lockSeconds?: number;
}

export interface SharedContentResult<TContent> {
  itemId: string;
  content: TContent;
  /** true = served from the library (no AI call); false = generated by this request. */
  reused: boolean;
  audio: SharedContentAudioResult | null;
}

interface AcquireRow {
  id: string;
  status: string;
  won: boolean;
  content: unknown;
  audio_status: string;
  audio_path: string | null;
  audio_mime_type: string | null;
  audio_voice: string | null;
  audio_locale: string | null;
  error_message: string | null;
}

function audioPathForItem(modality: SharedContentModality, itemId: string): string {
  // Deterministic by (modality, item id) only — no user, no timestamp; upsert is
  // safe and never creates a second object for the same item.
  return `${modality}/${itemId}.mp3`;
}

async function uploadItemAudio(client: SupabaseClient, path: string, bytes: Buffer, mimeType: string): Promise<void> {
  const { error } = await client.storage.from(SHARED_CONTENT_AUDIO_BUCKET).upload(path, bytes, {
    contentType: mimeType,
    upsert: true,
  });
  if (error) throw new Error(`SHARED_CONTENT_AUDIO_UPLOAD_FAILED: ${error.message}`);
}

async function downloadItemAudioBase64(client: SupabaseClient, path: string): Promise<string> {
  const { data, error } = await client.storage.from(SHARED_CONTENT_AUDIO_BUCKET).download(path);
  if (error || !data) throw new Error(`SHARED_CONTENT_AUDIO_DOWNLOAD_FAILED: ${error?.message ?? 'no data'}`);
  return Buffer.from(await data.arrayBuffer()).toString('base64');
}

async function persistContentReady(
  client: SupabaseClient,
  itemId: string,
  content: unknown,
  generatorModel: string | null | undefined,
): Promise<void> {
  const { error } = await client
    .from('shared_content_items')
    .update({ status: 'ready', content, generator_model: generatorModel ?? null, error_message: null, lock_expires_at: null })
    .eq('id', itemId);
  if (error) throw new Error(`SHARED_CONTENT_PERSIST_FAILED: ${error.message}`);
}

async function markContentFailed(client: SupabaseClient, itemId: string, err: unknown): Promise<void> {
  const message = (err instanceof Error ? err.message : String(err)).slice(0, 500);
  // Best-effort: the caller re-throws the ORIGINAL error regardless, so a DB
  // hiccup here never masks the real failure reason.
  await client
    .from('shared_content_items')
    .update({ status: 'failed', error_message: message, lock_expires_at: null })
    .eq('id', itemId)
    .then(() => {}, () => {});
}

async function registerUsage(
  client: SupabaseClient,
  userId: string,
  itemId: string,
  modality: SharedContentModality,
): Promise<void> {
  // Idempotent per (user, item): a retry never duplicates, and once recorded the
  // acquire RPC's NOT EXISTS permanently excludes this item from the user's
  // future selections (repetition avoidance). Never sets any performance data.
  await client
    .from('user_shared_content_usage')
    .upsert({ user_id: userId, shared_item_id: itemId, modality }, { onConflict: 'user_id,shared_item_id', ignoreDuplicates: true });
}

/**
 * Best-effort audio for a text-ready item. Claims a short audio lock (so two
 * concurrent readers don't both synthesize), synthesizes, uploads and persists.
 * Returns null (text-only this round) when it can't claim or when TTS fails — the
 * item is NEVER left advertising a broken audio path (§9). A prior audio failure
 * is repaired by the next request that reuses the item (no background job).
 */
async function ensureAudio<TContent>(
  client: SupabaseClient,
  modality: SharedContentModality,
  itemId: string,
  content: TContent,
  audio: SharedContentAudioSpec<TContent>,
): Promise<SharedContentAudioResult | null> {
  // Claim: only if audio is not already being produced (none/failed, or a
  // pending whose lock expired). Conditional UPDATE ... RETURNING is the lock.
  const nowIso = new Date().toISOString();
  const lockUntil = new Date(Date.now() + SHARED_CONTENT_AUDIO_LOCK_SECONDS * 1000).toISOString();
  const { data: claimedRows, error: claimErr } = await client
    .from('shared_content_items')
    .update({ audio_status: 'pending', audio_lock_expires_at: lockUntil })
    .eq('id', itemId)
    .in('audio_status', ['none', 'failed', 'pending'])
    .or(`audio_status.in.(none,failed),audio_lock_expires_at.lt.${nowIso}`)
    .select('id');
  if (claimErr) return null; // never fail the request over audio
  const claimed = Array.isArray(claimedRows) && claimedRows.length > 0;

  if (!claimed) {
    // Another request holds the audio lock. Read the current state: if it already
    // finished, serve it; otherwise serve text-only this round.
    const { data: cur } = await client
      .from('shared_content_items')
      .select('audio_status, audio_path, audio_mime_type, audio_voice, audio_locale')
      .eq('id', itemId)
      .maybeSingle();
    const c = cur as Pick<AcquireRow, 'audio_status' | 'audio_path' | 'audio_mime_type' | 'audio_voice' | 'audio_locale'> | null;
    if (c && c.audio_status === 'ready' && c.audio_path) {
      return { base64: await downloadItemAudioBase64(client, c.audio_path), mimeType: c.audio_mime_type ?? 'audio/mpeg', voice: c.audio_voice, locale: c.audio_locale };
    }
    return null;
  }

  try {
    const text = audio.extractText(content);
    const synth = await audio.synth(text);
    const path = audioPathForItem(modality, itemId);
    await uploadItemAudio(client, path, synth.audio, synth.mimeType);
    const { error: updErr } = await client
      .from('shared_content_items')
      .update({ audio_status: 'ready', audio_path: path, audio_mime_type: synth.mimeType, audio_voice: audio.voice, audio_locale: audio.locale, audio_lock_expires_at: null })
      .eq('id', itemId);
    if (updErr) return null;
    return { base64: synth.audio.toString('base64'), mimeType: synth.mimeType, voice: audio.voice, locale: audio.locale };
  } catch {
    // TTS/upload failed: mark failed so this is never a "complete audio" hit, but
    // keep the text usable. Client falls back to on-demand /api/tts as before.
    await client
      .from('shared_content_items')
      .update({ audio_status: 'failed', audio_lock_expires_at: null })
      .eq('id', itemId)
      .then(() => {}, () => {});
    return null;
  }
}

/**
 * The single entry point. Returns the compatible library item — reused when one
 * the user hasn't seen exists, otherwise generated NOW, persisted and served.
 */
export async function getOrCreateSharedContent<TContent>(
  opts: GetOrCreateSharedContentOptions<TContent>,
): Promise<SharedContentResult<TContent>> {
  const { client, userId, identity, generatorModel, generateContent, audio } = opts;
  const lockSeconds = opts.lockSeconds ?? SHARED_CONTENT_LOCK_SECONDS;

  // Time ONLY the DB acquire RPC (never the AI generateContent below), so the
  // db_latency degradation alert sees the shared-content DB path too. Fire-and-
  // forget: no-op unless the dashboard log level is on; adds no request latency.
  const t0 = Date.now();
  const { data, error } = await client.rpc('acquire_or_get_shared_content_item', {
    p_user_id: userId,
    p_modality: identity.modality,
    p_learning_language: identity.learningLanguage,
    p_interface_language: identity.interfaceLanguage,
    p_curriculum_version_id: identity.curriculumVersionId,
    p_subtopic_key: identity.subtopicKey,
    p_level_code: identity.levelCode,
    p_exercise_type: identity.exerciseType,
    p_template_key: identity.templateKey,
    p_prompt_version: identity.promptVersion,
    p_lock_duration_seconds: lockSeconds,
  });
  {
    const dt = Date.now() - t0;
    void recordServerTiming({
      endpoint: 'service:shared-content',
      stage: 'db:acquire_or_get',
      userId,
      durationMs: dt,
      dbMs: dt,
      provider: 'supabase',
      detail: { modality: identity.modality },
    });
  }
  if (error) throw new Error(`SHARED_CONTENT_ACQUIRE_RPC_FAILED: ${error.message}`);
  const row = (data as AcquireRow[] | null)?.[0];
  if (!row) throw new Error('SHARED_CONTENT_ACQUIRE_RETURNED_NO_ROW');

  // ── Cache MISS: this request won the slot and must generate now ─────────────
  if (row.won) {
    let content: TContent;
    try {
      content = await generateContent();
    } catch (err) {
      await markContentFailed(client, row.id, err);
      throw err;
    }
    await persistContentReady(client, row.id, content, generatorModel);
    const audioResult = audio ? await ensureAudio(client, identity.modality, row.id, content, audio) : null;
    await registerUsage(client, userId, row.id, identity.modality);
    return { itemId: row.id, content, reused: false, audio: audioResult };
  }

  // ── Cache HIT: reuse the ready item ─────────────────────────────────────────
  if (row.content == null) throw new Error('SHARED_CONTENT_READY_BUT_EMPTY');
  const content = row.content as TContent;
  let audioResult: SharedContentAudioResult | null = null;
  if (audio) {
    if (row.audio_status === 'ready' && row.audio_path) {
      audioResult = {
        base64: await downloadItemAudioBase64(client, row.audio_path),
        mimeType: row.audio_mime_type ?? 'audio/mpeg',
        voice: row.audio_voice,
        locale: row.audio_locale,
      };
    } else {
      // Text is a valid hit, but audio isn't ready yet (never generated, or a
      // prior failure): repair it on-demand so a compatible audio hit is complete
      // next time. Never served with a broken pointer.
      audioResult = await ensureAudio(client, identity.modality, row.id, content, audio);
    }
  }
  await registerUsage(client, userId, row.id, identity.modality);
  return { itemId: row.id, content, reused: true, audio: audioResult };
}

/**
 * Derives the CEFR level from a recorte key (level is the first segment, e.g.
 * "B1.OPINION.AGREE" -> "B1"). Used to populate level_code consistently across
 * modalities. Correctness of reuse does not depend on it — (version, subtopic)
 * already pin the level — but it is a real compatibility attribute.
 */
export function levelCodeFromSubtopicKey(subtopicKey: string): string {
  const head = subtopicKey.split('.')[0] ?? '';
  return /^[A-Za-z]\d$/.test(head) ? head.toUpperCase() : '';
}
