import { GrammarTopic } from '../grammar-types';

export const A1_TOPICS: readonly GrammarTopic[] = [
  {
    id: 'grammar.pronouns.subject',
    version: 1,
    slug: 'subject-pronouns',
    title: { en: 'Subject Pronouns', ptBR: 'Pronomes Pessoais (Sujeito)' },
    category: 'pronoun',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A1',
    prerequisites: [],
    relatedTopics: ['grammar.pronouns.object_basic', 'grammar.possessives.adjectives'],
    communicativeUses: [
      'Identificar quem realiza a ação',
      'Substituir nomes de pessoas e coisas para evitar repetição',
    ],
    structures: {
      affirmative: ['I, you, he, she, it, we, they + verb'],
    },
    examples: [
      { en: 'I am a student.', ptBR: 'Eu sou estudante.', stage: 'guided_practice' },
      { en: 'She works at a hospital.', ptBR: 'Ela trabalha num hospital.', stage: 'independent_production' },
      { en: 'They are from Brazil.', ptBR: 'Eles são do Brasil.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'Me am tired.', correct: 'I am tired.', explanationPtBR: 'Use "I" como sujeito, nunca "me".' },
    ],
    generationRules: {
      notesForGenerator: ['Sempre presentes implicitamente; não precisam ser o foco principal de uma missão A1 isolada.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'substitution', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['pronouns', 'a1', 'foundation'],
    isActive: true,
  },
  {
    id: 'grammar.pronouns.object_basic',
    version: 1,
    slug: 'object-pronouns-basic',
    title: { en: 'Object Pronouns (Basic)', ptBR: 'Pronomes Objeto (Básico)' },
    category: 'pronoun',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'A2',
    prerequisites: ['grammar.pronouns.subject'],
    relatedTopics: ['grammar.pronouns.subject', 'grammar.possessives.adjectives'],
    communicativeUses: [
      'Substituir o objeto de uma frase para evitar repetição',
      'Falar sobre pessoas e coisas de forma natural',
    ],
    structures: {
      affirmative: ['Subject + verb + me/you/him/her/it/us/them'],
    },
    examples: [
      { en: 'She called me yesterday.', ptBR: 'Ela me ligou ontem.', stage: 'guided_practice' },
      { en: 'Can you help him?', ptBR: 'Você pode ajudá-lo?', stage: 'independent_production' },
      { en: 'I love it!', ptBR: 'Eu adoro isso!', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'She called I.', correct: 'She called me.', explanationPtBR: 'Após um verbo, use pronome objeto (me), não sujeito (I).' },
    ],
    generationRules: {
      notesForGenerator: ['Introduzir em contextos com verbos de ação simples (call, help, see, know).'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'substitution'],
      evidenceRequiredForMastery: 8,
    },
    tags: ['pronouns', 'a1', 'foundation'],
    isActive: true,
  },
  {
    id: 'grammar.possessives.adjectives',
    version: 1,
    slug: 'possessive-adjectives',
    title: { en: 'Possessive Adjectives', ptBR: 'Adjetivos Possessivos' },
    category: 'adjective',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A2',
    prerequisites: ['grammar.pronouns.subject'],
    relatedTopics: ['grammar.pronouns.subject', 'grammar.pronouns.object_basic'],
    communicativeUses: [
      'Indicar posse ou pertencimento',
      'Falar sobre família, pertences e características pessoais',
    ],
    structures: {
      affirmative: ['my, your, his, her, its, our, their + noun'],
    },
    examples: [
      { en: 'This is my book.', ptBR: 'Este é o meu livro.', stage: 'guided_practice' },
      { en: 'Her name is Ana.', ptBR: 'O nome dela é Ana.', stage: 'independent_production' },
      { en: 'We love our city.', ptBR: 'Nós amamos nossa cidade.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'This is he book.', correct: 'This is his book.', explanationPtBR: 'Use o adjetivo possessivo (his), não o pronome sujeito (he).' },
      { incorrect: "She likes her's job.", correct: 'She likes her job.', explanationPtBR: 'Adjetivos possessivos não recebem apóstrofo.' },
    ],
    generationRules: {
      notesForGenerator: ['Comum em apresentações pessoais e descrições de família.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 8,
    },
    tags: ['possessives', 'a1', 'foundation'],
    isActive: true,
  },
  {
    id: 'grammar.verb_to_be.present',
    version: 1,
    slug: 'verb-to-be-present',
    title: { en: 'Verb To Be (Present)', ptBR: 'Verbo To Be (Presente)' },
    category: 'verb_form',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A2',
    prerequisites: ['grammar.pronouns.subject'],
    relatedTopics: ['grammar.verb_to_be.past', 'grammar.present_continuous', 'grammar.there_is_are'],
    communicativeUses: [
      'Descrever identidade, profissão e nacionalidade',
      'Indicar localização',
      'Expressar estado e condição',
      'Formar o presente contínuo',
    ],
    structures: {
      affirmative: ["I am (I'm)", "You/We/They are ('re)", "He/She/It is ('s)"],
      negative: ["I am not (I'm not)", "You/We/They are not (aren't)", "He/She/It is not (isn't)"],
      interrogative: ['Am I?', 'Are you/we/they?', 'Is he/she/it?'],
    },
    examples: [
      { en: "I'm a software developer.", ptBR: 'Sou desenvolvedor de software.', stage: 'guided_practice' },
      { en: 'She is from São Paulo.', ptBR: 'Ela é de São Paulo.', stage: 'independent_production' },
      { en: 'Are you okay?', ptBR: 'Você está bem?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'She are happy.', correct: 'She is happy.', explanationPtBR: 'Com he/she/it, use "is".' },
      { incorrect: 'He am tired.', correct: 'He is tired.', explanationPtBR: '"Am" é apenas para "I".' },
    ],
    generationRules: {
      notesForGenerator: ['Pré-requisito para present continuous e there is/are. Priorizar em missões de apresentação pessoal.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 15,
    },
    tags: ['verb_to_be', 'a1', 'foundation', 'high_frequency'],
    isActive: true,
  },
  {
    id: 'grammar.have_has',
    version: 1,
    slug: 'have-has',
    title: { en: 'Have / Has (Possession)', ptBR: 'Have / Has (Posse)' },
    category: 'verb_form',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A2',
    prerequisites: ['grammar.verb_to_be.present'],
    relatedTopics: ['grammar.present_simple', 'grammar.present_perfect.intro'],
    communicativeUses: [
      'Expressar posse',
      'Descrever características físicas',
      'Falar sobre família e pertences',
    ],
    structures: {
      affirmative: ['I/You/We/They have + noun', 'He/She/It has + noun'],
      negative: ["I/You/We/They don't have + noun", "He/She/It doesn't have + noun"],
      interrogative: ['Do you have...?', 'Does she have...?'],
    },
    examples: [
      { en: 'I have two brothers.', ptBR: 'Eu tenho dois irmãos.', stage: 'guided_practice' },
      { en: 'She has a dog.', ptBR: 'Ela tem um cachorro.', stage: 'independent_production' },
      { en: 'Do you have a car?', ptBR: 'Você tem carro?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'She have a car.', correct: 'She has a car.', explanationPtBR: 'Com he/she/it, use "has".' },
    ],
    generationRules: {
      notesForGenerator: ['Comum em descrições pessoais e de família. Não confundir com "have" auxiliar do present perfect.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['have_has', 'a1', 'possession'],
    isActive: true,
  },
  {
    id: 'grammar.present_simple',
    version: 1,
    slug: 'present-simple',
    title: { en: 'Present Simple', ptBR: 'Presente Simples' },
    category: 'verb_tense',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A2',
    prerequisites: ['grammar.pronouns.subject', 'grammar.verb_to_be.present'],
    relatedTopics: ['grammar.present_continuous', 'grammar.adverbs.frequency', 'grammar.negation.basic'],
    communicativeUses: [
      'Descrever hábitos e rotinas',
      'Expressar fatos e verdades gerais',
      'Expressar sentimentos e estados permanentes',
      'Programações fixas no futuro',
    ],
    structures: {
      affirmative: ['Subject + verb base (+ s/es para he/she/it)'],
      negative: ['Subject + do/does + not + verb base'],
      interrogative: ['Do/Does + subject + verb base?'],
    },
    examples: [
      { en: 'I work from home every day.', ptBR: 'Eu trabalho em casa todos os dias.', stage: 'guided_practice' },
      { en: "She doesn't eat meat.", ptBR: 'Ela não come carne.', stage: 'independent_production' },
      { en: 'Do you speak English?', ptBR: 'Você fala inglês?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'She work in São Paulo.', correct: 'She works in São Paulo.', explanationPtBR: 'Com he/she/it, o verbo recebe -s ou -es.' },
      { incorrect: "He don't like coffee.", correct: "He doesn't like coffee.", explanationPtBR: 'Com he/she/it, use "doesn\'t" na negativa.' },
    ],
    generationRules: {
      allowedContexts: ['rotinas', 'hábitos', 'preferências', 'fatos gerais'],
      notesForGenerator: ['Tópico central do A1. Ideal para missões sobre rotinas, trabalho e vida cotidiana.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction', 'multiple_choice'],
      evidenceRequiredForMastery: 20,
      requiredContextsForMastery: 3,
    },
    tags: ['present_simple', 'a1', 'high_frequency', 'foundation'],
    isActive: true,
  },
  {
    id: 'grammar.present_continuous',
    version: 1,
    slug: 'present-continuous',
    title: { en: 'Present Continuous', ptBR: 'Presente Contínuo' },
    category: 'verb_tense',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A2',
    prerequisites: ['grammar.verb_to_be.present', 'grammar.present_simple'],
    relatedTopics: ['grammar.present_simple', 'grammar.future.going_to', 'grammar.gerunds.basic'],
    communicativeUses: [
      'Descrever o que está acontecendo agora',
      'Ações temporárias em andamento',
      'Planos futuros já confirmados',
      'Mudanças e tendências',
    ],
    structures: {
      affirmative: ['Subject + am/is/are + verb-ing'],
      negative: ['Subject + am/is/are + not + verb-ing'],
      interrogative: ['Am/Is/Are + subject + verb-ing?'],
    },
    examples: [
      { en: "I'm working on a new project.", ptBR: 'Estou trabalhando em um novo projeto.', stage: 'guided_practice' },
      { en: "They aren't coming tonight.", ptBR: 'Eles não estão vindo hoje à noite.', stage: 'independent_production' },
      { en: 'Are you listening?', ptBR: 'Você está ouvindo?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I am knowing the answer.', correct: 'I know the answer.', explanationPtBR: 'Verbos de estado (know, believe, want) não usam -ing.' },
    ],
    generationRules: {
      allowedContexts: ['ações no momento', 'situações temporárias'],
      forbiddenCombinations: ['stative verbs with -ing'],
      notesForGenerator: ['Requer verb to be como base. Comum em descrições de situação atual.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 15,
    },
    tags: ['present_continuous', 'a1', 'high_frequency'],
    isActive: true,
  },
  {
    id: 'grammar.imperatives',
    version: 1,
    slug: 'imperatives',
    title: { en: 'Imperatives', ptBR: 'Imperativos' },
    category: 'verb_form',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A1',
    prerequisites: ['grammar.present_simple'],
    relatedTopics: ['grammar.present_simple', 'grammar.negation.basic'],
    communicativeUses: [
      'Dar instruções e direções',
      'Fazer pedidos',
      'Dar conselhos simples',
      'Avisos e proibições',
    ],
    structures: {
      affirmative: ['Verb base (without subject): "Open the door."'],
      negative: ["Don't + verb base: \"Don't be late.\""],
    },
    examples: [
      { en: 'Open your books to page 5.', ptBR: 'Abram seus livros na página 5.', stage: 'guided_practice' },
      { en: "Don't forget to call me.", ptBR: 'Não se esqueça de me ligar.', stage: 'independent_production' },
      { en: 'Please sit down.', ptBR: 'Por favor, sente-se.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'You open the door.', correct: 'Open the door.', explanationPtBR: 'Imperativos não usam sujeito explícito.' },
    ],
    generationRules: {
      allowedContexts: ['instruções', 'direções', 'receitas', 'pedidos educados'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 8,
    },
    tags: ['imperatives', 'a1', 'instructions'],
    isActive: true,
  },
  {
    id: 'grammar.can',
    version: 1,
    slug: 'can-cannot',
    title: { en: 'Can / Cannot (Ability)', ptBR: 'Can / Cannot (Habilidade)' },
    category: 'modal',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A2',
    prerequisites: ['grammar.present_simple'],
    relatedTopics: ['grammar.present_simple', 'grammar.modals.should', 'grammar.modals.may_might'],
    communicativeUses: [
      'Expressar habilidade ou capacidade',
      'Pedir permissão de forma simples',
      'Fazer pedidos educados',
      'Oferecer ajuda',
    ],
    structures: {
      affirmative: ['Subject + can + verb base'],
      negative: ["Subject + cannot (can't) + verb base"],
      interrogative: ['Can + subject + verb base?'],
    },
    examples: [
      { en: 'I can speak three languages.', ptBR: 'Eu falo três idiomas.', stage: 'guided_practice' },
      { en: "She can't drive yet.", ptBR: 'Ela ainda não sabe dirigir.', stage: 'independent_production' },
      { en: 'Can you help me with this?', ptBR: 'Você pode me ajudar com isso?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'She can to swim.', correct: 'She can swim.', explanationPtBR: 'Depois de "can", use o verbo base sem "to".' },
    ],
    generationRules: {
      allowedContexts: ['habilidades', 'permissões simples', 'pedidos educados'],
      notesForGenerator: ['Primeira exposição a modais. Manter simples — habilidade presente.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['can', 'modal', 'a1', 'ability'],
    isActive: true,
  },
  {
    id: 'grammar.articles',
    version: 1,
    slug: 'articles',
    title: { en: 'Articles (a, an, the)', ptBR: 'Artigos (a, an, the)' },
    category: 'article',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.pronouns.subject'],
    relatedTopics: ['grammar.nouns.plural_regular', 'grammar.nouns.countable_uncountable_basic', 'grammar.demonstratives'],
    communicativeUses: [
      'Introduzir um substantivo pela primeira vez (a/an)',
      'Referir a algo já mencionado ou específico (the)',
      'Generalizar (zero article)',
    ],
    structures: {
      affirmative: ['a + consonant sound noun', 'an + vowel sound noun', 'the + specific noun'],
    },
    examples: [
      { en: 'I have a dog and a cat.', ptBR: 'Eu tenho um cachorro e um gato.', stage: 'guided_practice' },
      { en: 'The dog is sleeping.', ptBR: 'O cachorro está dormindo.', stage: 'independent_production' },
      { en: 'She is an engineer.', ptBR: 'Ela é engenheira.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'She is a engineer.', correct: 'She is an engineer.', explanationPtBR: 'Use "an" antes de sons vocálicos.' },
      { incorrect: 'I love the music.', correct: 'I love music.', explanationPtBR: 'Para generalizações, não use artigo.' },
    ],
    generationRules: {
      notesForGenerator: ['Artigos são um ponto de dificuldade persistente para falantes de português. Retornar frequentemente.'],
    },
    assessment: {
      opportunityTypes: ['gap_fill', 'error_correction', 'free_production'],
      evidenceRequiredForMastery: 20,
      requiredContextsForMastery: 4,
    },
    tags: ['articles', 'a1', 'high_frequency', 'persistent_challenge'],
    isActive: true,
  },
  {
    id: 'grammar.nouns.plural_regular',
    version: 1,
    slug: 'plural-regular-nouns',
    title: { en: 'Regular Plural Nouns', ptBR: 'Plural Regular de Substantivos' },
    category: 'noun',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A1',
    prerequisites: ['grammar.articles'],
    relatedTopics: ['grammar.articles', 'grammar.demonstratives', 'grammar.there_is_are'],
    communicativeUses: [
      'Referir a mais de uma pessoa ou coisa',
      'Fazer listas',
    ],
    structures: {
      affirmative: ['noun + -s (cats, dogs)', 'noun ending in -s/-sh/-ch/-x/-z + -es (buses, dishes)', 'consonant + y → -ies (cities, babies)'],
    },
    examples: [
      { en: 'I have two cats and three dogs.', ptBR: 'Eu tenho dois gatos e três cachorros.', stage: 'guided_practice' },
      { en: 'The cities are beautiful.', ptBR: 'As cidades são bonitas.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'two childs', correct: 'two children', explanationPtBR: '"Child" tem plural irregular: children.' },
    ],
    generationRules: {
      notesForGenerator: ['Incluir apenas plurais regulares em A1. Irregulares (children, men, women) são exposição A1, produção A2.'],
    },
    assessment: {
      opportunityTypes: ['gap_fill', 'sentence_completion'],
      evidenceRequiredForMastery: 8,
    },
    tags: ['nouns', 'plural', 'a1', 'foundation'],
    isActive: true,
  },
  {
    id: 'grammar.demonstratives',
    version: 1,
    slug: 'demonstratives',
    title: { en: 'Demonstratives (this, that, these, those)', ptBR: 'Demonstrativos (this, that, these, those)' },
    category: 'determiner',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A1',
    prerequisites: ['grammar.articles', 'grammar.nouns.plural_regular'],
    relatedTopics: ['grammar.articles', 'grammar.nouns.plural_regular'],
    communicativeUses: [
      'Indicar proximidade ou distância de objetos e pessoas',
      'Apresentar itens',
    ],
    structures: {
      affirmative: ['this/that + singular noun', 'these/those + plural noun'],
    },
    examples: [
      { en: 'This book is interesting.', ptBR: 'Este livro é interessante.', stage: 'guided_practice' },
      { en: 'Those shoes are expensive.', ptBR: 'Aqueles sapatos são caros.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'These book is mine.', correct: 'This book is mine.', explanationPtBR: '"These" é plural. Use "this" com substantivo singular.' },
    ],
    generationRules: {},
    assessment: {
      opportunityTypes: ['gap_fill', 'sentence_completion'],
      evidenceRequiredForMastery: 6,
    },
    tags: ['demonstratives', 'a1'],
    isActive: true,
  },
  {
    id: 'grammar.there_is_are',
    version: 1,
    slug: 'there-is-are',
    title: { en: 'There is / There are', ptBR: 'There is / There are (Existe/Existem)' },
    category: 'verb_form',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A2',
    prerequisites: ['grammar.verb_to_be.present', 'grammar.nouns.plural_regular'],
    relatedTopics: ['grammar.verb_to_be.present', 'grammar.nouns.countable_uncountable_basic'],
    communicativeUses: [
      'Indicar a existência de algo',
      'Descrever lugares e espaços',
      'Listar itens em um lugar',
    ],
    structures: {
      affirmative: ['There is + singular noun', 'There are + plural noun'],
      negative: ["There isn't a...", "There aren't any..."],
      interrogative: ['Is there a...?', 'Are there any...?'],
    },
    examples: [
      { en: 'There is a café near my office.', ptBR: 'Há um café perto do meu escritório.', stage: 'guided_practice' },
      { en: 'There are many parks in this city.', ptBR: 'Há muitos parques nesta cidade.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'There are a book on the table.', correct: 'There is a book on the table.', explanationPtBR: 'Use "there is" com singular e "there are" com plural.' },
    ],
    generationRules: {
      allowedContexts: ['descrições de lugares', 'listas de itens'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 8,
    },
    tags: ['there_is_are', 'a1', 'existence'],
    isActive: true,
  },
  {
    id: 'grammar.questions.basic',
    version: 1,
    slug: 'basic-questions',
    title: { en: 'Basic Questions (Wh- and Yes/No)', ptBR: 'Perguntas Básicas (Wh- e Sim/Não)' },
    category: 'question',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A2',
    prerequisites: ['grammar.verb_to_be.present', 'grammar.present_simple'],
    relatedTopics: ['grammar.present_simple', 'grammar.negation.basic', 'grammar.question_tags'],
    communicativeUses: [
      'Obter informações sobre pessoas, lugares e coisas',
      'Confirmar ou negar afirmações',
      'Iniciar e manter conversas',
    ],
    structures: {
      interrogative: [
        'Wh- word + am/is/are + subject?',
        'Wh- word + do/does + subject + verb?',
        'Am/Is/Are + subject + ?',
        'Do/Does + subject + verb?',
      ],
    },
    examples: [
      { en: 'Where do you work?', ptBR: 'Onde você trabalha?', stage: 'guided_practice' },
      { en: 'What time is it?', ptBR: 'Que horas são?', stage: 'independent_production' },
      { en: 'Do you like coffee?', ptBR: 'Você gosta de café?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'Where you work?', correct: 'Where do you work?', explanationPtBR: 'Use o auxiliar "do/does" em perguntas com verbos que não são "to be".' },
    ],
    generationRules: {
      notesForGenerator: ['Perguntas básicas são essenciais para conversação A1. Incluir em missões de interação social.'],
    },
    assessment: {
      opportunityTypes: ['question_formation', 'free_production'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['questions', 'a1', 'high_frequency', 'communication'],
    isActive: true,
  },
  {
    id: 'grammar.negation.basic',
    version: 1,
    slug: 'basic-negation',
    title: { en: 'Basic Negation', ptBR: 'Negação Básica' },
    category: 'negation',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A2',
    prerequisites: ['grammar.present_simple'],
    relatedTopics: ['grammar.present_simple', 'grammar.verb_to_be.present', 'grammar.questions.basic'],
    communicativeUses: [
      'Negar fatos e afirmações',
      'Corrigir informações incorretas',
      'Expressar o que não é verdade ou não acontece',
    ],
    structures: {
      negative: [
        'Subject + am/is/are + not + ...',
        'Subject + do/does + not + verb base',
      ],
    },
    examples: [
      { en: "I'm not from São Paulo.", ptBR: 'Não sou de São Paulo.', stage: 'guided_practice' },
      { en: "She doesn't speak French.", ptBR: 'Ela não fala francês.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: "She don't like it.", correct: "She doesn't like it.", explanationPtBR: 'Com he/she/it, use "doesn\'t" na negativa.' },
    ],
    generationRules: {},
    assessment: {
      opportunityTypes: ['sentence_completion', 'error_correction'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['negation', 'a1', 'foundation'],
    isActive: true,
  },
  {
    id: 'grammar.adverbs.frequency',
    version: 1,
    slug: 'adverbs-of-frequency',
    title: { en: 'Adverbs of Frequency', ptBR: 'Advérbios de Frequência' },
    category: 'adverb',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'A2',
    prerequisites: ['grammar.present_simple'],
    relatedTopics: ['grammar.present_simple', 'grammar.adverbs.frequency'],
    communicativeUses: [
      'Indicar com que frequência algo acontece',
      'Descrever rotinas e hábitos com precisão',
    ],
    structures: {
      affirmative: ['Subject + frequency adverb + main verb', 'always, usually, often, sometimes, rarely, never'],
      other: ['Position: before main verb, after "to be"'],
    },
    examples: [
      { en: 'I always drink coffee in the morning.', ptBR: 'Eu sempre tomo café de manhã.', stage: 'guided_practice' },
      { en: 'She is never late.', ptBR: 'Ela nunca se atrasa.', stage: 'independent_production' },
      { en: 'We sometimes work on weekends.', ptBR: 'Às vezes trabalhamos nos fins de semana.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I drink always coffee.', correct: 'I always drink coffee.', explanationPtBR: 'O advérbio de frequência vem antes do verbo principal (mas depois do "to be").' },
    ],
    generationRules: {
      allowedContexts: ['rotinas', 'hábitos', 'estilo de vida'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 8,
    },
    tags: ['adverbs', 'frequency', 'a1'],
    isActive: true,
  },
  {
    id: 'grammar.prepositions.time_place_basic',
    version: 1,
    slug: 'prepositions-time-place-basic',
    title: { en: 'Basic Prepositions of Time and Place', ptBR: 'Preposições Básicas de Tempo e Lugar' },
    category: 'preposition',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A1',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.present_simple'],
    relatedTopics: ['grammar.present_simple', 'grammar.there_is_are'],
    communicativeUses: [
      'Indicar localização de pessoas e objetos',
      'Expressar tempo: hora, dia, mês, ano',
      'Descrever rotas e direções simples',
    ],
    structures: {
      other: [
        'Place: in, on, at, under, next to, between, behind, in front of',
        'Time: at (hour), on (day/date), in (month/year/season)',
      ],
    },
    examples: [
      { en: 'The meeting is on Monday at 3 pm.', ptBR: 'A reunião é na segunda às 15h.', stage: 'guided_practice' },
      { en: 'She lives in São Paulo.', ptBR: 'Ela mora em São Paulo.', stage: 'independent_production' },
      { en: 'The keys are on the table.', ptBR: 'As chaves estão na mesa.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I was born in 1990 in January.', correct: 'I was born in January 1990.', explanationPtBR: 'Use "in" para mês e para ano.' },
      { incorrect: 'at the morning', correct: 'in the morning', explanationPtBR: 'Use "in the morning/afternoon/evening", não "at".' },
    ],
    generationRules: {
      notesForGenerator: ['Preposições são frequentemente confundidas por falantes de português. Repetição em múltiplos contextos é essencial.'],
    },
    assessment: {
      opportunityTypes: ['gap_fill', 'sentence_completion', 'error_correction'],
      evidenceRequiredForMastery: 15,
      requiredContextsForMastery: 3,
    },
    tags: ['prepositions', 'a1', 'time', 'place', 'persistent_challenge'],
    isActive: true,
  },
  {
    id: 'grammar.nouns.countable_uncountable_basic',
    version: 1,
    slug: 'countable-uncountable-nouns-basic',
    title: { en: 'Countable and Uncountable Nouns (Basic)', ptBR: 'Substantivos Contáveis e Incontáveis (Básico)' },
    category: 'noun',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.articles', 'grammar.nouns.plural_regular'],
    relatedTopics: ['grammar.articles', 'grammar.determiners.some_any', 'grammar.determiners.quantity_basic'],
    communicativeUses: [
      'Distinguir o que pode ser contado do que não pode',
      'Usar artigos e quantificadores corretamente',
    ],
    structures: {
      other: [
        'Countable: a book, two books, some books',
        'Uncountable: water, information, advice (no plural, no a/an)',
      ],
    },
    examples: [
      { en: 'Can I have some water?', ptBR: 'Posso pegar um pouco de água?', stage: 'guided_practice' },
      { en: 'I need some advice.', ptBR: 'Preciso de um conselho.', stage: 'exposure' },
    ],
    commonErrors: [
      { incorrect: 'an information', correct: 'some information / a piece of information', explanationPtBR: '"Information" é incontável em inglês.' },
    ],
    generationRules: {
      notesForGenerator: ['A1 exposição; A2 produção guiada. Focar em itens comuns: water, food, money, time, advice.'],
    },
    assessment: {
      opportunityTypes: ['gap_fill', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['nouns', 'countable', 'uncountable', 'a1'],
    isActive: true,
  },
  {
    id: 'grammar.determiners.some_any',
    version: 1,
    slug: 'some-any',
    title: { en: 'Some and Any', ptBR: 'Some e Any' },
    category: 'determiner',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A1',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.nouns.countable_uncountable_basic'],
    relatedTopics: ['grammar.nouns.countable_uncountable_basic', 'grammar.determiners.quantity_basic'],
    communicativeUses: [
      'Expressar quantidade indeterminada em afirmações e perguntas',
      'Negar a existência de algo',
    ],
    structures: {
      affirmative: ['some + plural/uncountable noun (affirmatives, offers)'],
      negative: ['any + plural/uncountable noun (negatives, questions)'],
      interrogative: ['any + plural/uncountable noun (questions)'],
    },
    examples: [
      { en: 'I have some friends in London.', ptBR: 'Eu tenho alguns amigos em Londres.', stage: 'guided_practice' },
      { en: "I don't have any money right now.", ptBR: 'Não tenho dinheiro agora.', stage: 'independent_production' },
      { en: 'Do you have any questions?', ptBR: 'Você tem alguma pergunta?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I have some questions? (in a question)', correct: 'Do you have any questions?', explanationPtBR: 'Use "any" em perguntas e negativas. "Some" em perguntas apenas quando é uma oferta.' },
    ],
    generationRules: {},
    assessment: {
      opportunityTypes: ['gap_fill', 'sentence_completion'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['determiners', 'some', 'any', 'a1'],
    isActive: true,
  },
  {
    id: 'grammar.determiners.quantity_basic',
    version: 1,
    slug: 'quantity-basic',
    title: { en: 'Much, Many and A Lot Of (Basic)', ptBR: 'Much, Many e A Lot Of (Introdutório)' },
    category: 'determiner',
    minimumExposureLevel: 'A1',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.nouns.countable_uncountable_basic'],
    relatedTopics: ['grammar.nouns.countable_uncountable_basic', 'grammar.determiners.some_any'],
    communicativeUses: [
      'Expressar grandes quantidades de forma correta',
    ],
    structures: {
      other: [
        'much + uncountable noun (questions/negatives)',
        'many + countable plural noun (questions/negatives)',
        'a lot of + any noun (affirmatives)',
      ],
    },
    examples: [
      { en: 'There are a lot of people here.', ptBR: 'Há muita gente aqui.', stage: 'guided_practice' },
      { en: "I don't have much time.", ptBR: 'Não tenho muito tempo.', stage: 'guided_practice' },
      { en: 'How many students are in the class?', ptBR: 'Quantos alunos há na turma?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I have many money.', correct: 'I have a lot of money.', explanationPtBR: '"Much" é para incontáveis, "many" para contáveis. "A lot of" funciona para ambos.' },
    ],
    generationRules: {},
    assessment: {
      opportunityTypes: ['gap_fill', 'error_correction'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['determiners', 'quantity', 'a1', 'a2'],
    isActive: true,
  },
] as const satisfies readonly GrammarTopic[];
