import { GrammarTopic } from '../grammar-types';

export const A2_TOPICS: readonly GrammarTopic[] = [
  {
    id: 'grammar.verb_to_be.past',
    version: 1,
    slug: 'verb-to-be-past',
    title: { en: 'Verb To Be (Past)', ptBR: 'Verbo To Be (Passado)' },
    category: 'verb_form',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'A2',
    prerequisites: ['grammar.verb_to_be.present'],
    relatedTopics: ['grammar.verb_to_be.present', 'grammar.past_simple', 'grammar.past_continuous'],
    communicativeUses: [
      'Descrever estados e condições no passado',
      'Falar sobre onde alguém estava',
      'Descrever como algo era antes',
    ],
    structures: {
      affirmative: ['I/He/She/It was + ...', 'You/We/They were + ...'],
      negative: ["I/He/She/It wasn't + ...", "You/We/They weren't + ..."],
      interrogative: ['Was I/he/she/it + ...?', 'Were you/we/they + ...?'],
    },
    examples: [
      { en: 'I was very tired yesterday.', ptBR: 'Eu estava muito cansado ontem.', stage: 'guided_practice' },
      { en: 'They were at the conference last week.', ptBR: 'Eles estavam na conferência semana passada.', stage: 'independent_production' },
      { en: 'Was she at home?', ptBR: 'Ela estava em casa?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'They was happy.', correct: 'They were happy.', explanationPtBR: 'Com you/we/they, use "were", não "was".' },
      { incorrect: 'He were late.', correct: 'He was late.', explanationPtBR: 'Com I/he/she/it, use "was".' },
    ],
    generationRules: {
      allowedContexts: ['narrativas passadas', 'descrições de situações anteriores'],
      notesForGenerator: ['Base para past continuous. Priorizar em contextos narrativos e descritivos do passado.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['verb_to_be', 'past', 'a2', 'foundation'],
    isActive: true,
  },
  {
    id: 'grammar.past_simple',
    version: 1,
    slug: 'past-simple',
    title: { en: 'Past Simple', ptBR: 'Passado Simples' },
    category: 'verb_tense',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.present_simple', 'grammar.verb_to_be.past'],
    relatedTopics: ['grammar.past_continuous', 'grammar.present_perfect.intro', 'grammar.narrative_tenses'],
    communicativeUses: [
      'Relatar eventos completos no passado',
      'Contar histórias e experiências',
      'Descrever sequências de ações passadas',
      'Falar sobre hábitos passados (com "used to")',
    ],
    structures: {
      affirmative: ['Subject + verb-ed (regular) / irregular past form'],
      negative: ["Subject + didn't + verb base"],
      interrogative: ['Did + subject + verb base?'],
    },
    examples: [
      { en: 'I worked late last night.', ptBR: 'Trabalhei até tarde ontem à noite.', stage: 'guided_practice' },
      { en: "She didn't come to the meeting.", ptBR: 'Ela não veio à reunião.', stage: 'independent_production' },
      { en: 'Did you enjoy the trip?', ptBR: 'Você curtiu a viagem?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: "I didn't worked yesterday.", correct: "I didn't work yesterday.", explanationPtBR: 'Após "didn\'t", use sempre o verbo base, nunca a forma passada.' },
      { incorrect: 'She goed to the store.', correct: 'She went to the store.', explanationPtBR: '"Go" tem passado irregular: "went".' },
    ],
    generationRules: {
      allowedContexts: ['narrativas', 'relatos de experiências', 'histórias'],
      notesForGenerator: ['Incluir tanto verbos regulares (-ed) quanto os irregulares mais comuns (go/went, have/had, see/saw, etc.).'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction', 'narrative_writing'],
      evidenceRequiredForMastery: 20,
      requiredContextsForMastery: 3,
    },
    tags: ['past_simple', 'a2', 'high_frequency'],
    isActive: true,
  },
  {
    id: 'grammar.past_continuous',
    version: 1,
    slug: 'past-continuous',
    title: { en: 'Past Continuous (Introductory)', ptBR: 'Passado Contínuo (Introdução)' },
    category: 'verb_tense',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.past_simple', 'grammar.verb_to_be.past'],
    relatedTopics: ['grammar.past_simple', 'grammar.narrative_tenses', 'grammar.present_continuous'],
    communicativeUses: [
      'Descrever ação em progresso em um momento do passado',
      'Criar contexto de fundo em narrativas',
      'Indicar duas ações simultâneas no passado',
    ],
    structures: {
      affirmative: ['Subject + was/were + verb-ing'],
      negative: ["Subject + wasn't/weren't + verb-ing"],
      interrogative: ['Was/Were + subject + verb-ing?'],
    },
    examples: [
      { en: 'I was watching TV when she called.', ptBR: 'Eu estava assistindo TV quando ela ligou.', stage: 'guided_practice' },
      { en: 'They were having lunch at noon.', ptBR: 'Eles estavam almoçando ao meio-dia.', stage: 'independent_production' },
      { en: 'What were you doing last night?', ptBR: 'O que você estava fazendo ontem à noite?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I was work when she arrived.', correct: 'I was working when she arrived.', explanationPtBR: 'O past continuous usa was/were + verbo-ing, não o verbo base.' },
    ],
    generationRules: {
      allowedContexts: ['narrativas', 'descrição de cenas passadas'],
      notesForGenerator: ['Frequentemente aparece com past simple (when/while). Introduzir em par com past simple.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'narrative_writing', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['past_continuous', 'a2', 'narrative'],
    isActive: true,
  },
  {
    id: 'grammar.future.going_to',
    version: 1,
    slug: 'future-going-to',
    title: { en: 'Future with Going To', ptBR: 'Futuro com Going To' },
    category: 'verb_tense',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.verb_to_be.present', 'grammar.present_simple'],
    relatedTopics: ['grammar.future.will', 'grammar.present_continuous', 'grammar.future_continuous.intro'],
    communicativeUses: [
      'Expressar planos e intenções futuras',
      'Fazer previsões baseadas em evidências presentes',
      'Falar sobre decisões já tomadas',
    ],
    structures: {
      affirmative: ["Subject + am/is/are + going to + verb base"],
      negative: ["Subject + am/is/are + not + going to + verb base"],
      interrogative: ['Am/Is/Are + subject + going to + verb base?'],
    },
    examples: [
      { en: "I'm going to start a new project next month.", ptBR: 'Vou começar um novo projeto no mês que vem.', stage: 'guided_practice' },
      { en: "She isn't going to attend the meeting.", ptBR: 'Ela não vai participar da reunião.', stage: 'independent_production' },
      { en: 'Are you going to apply for the job?', ptBR: 'Você vai se candidatar para o emprego?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I am going to started.', correct: 'I am going to start.', explanationPtBR: 'Depois de "going to", use sempre o verbo base.' },
    ],
    generationRules: {
      allowedContexts: ['planos futuros', 'intenções', 'previsões com evidência'],
      notesForGenerator: ['Contrastar com "will" para espontaneidade vs. planos. Usar "going to" para decisões anteriores.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['future', 'going_to', 'a2'],
    isActive: true,
  },
  {
    id: 'grammar.future.will',
    version: 1,
    slug: 'future-will',
    title: { en: 'Future with Will', ptBR: 'Futuro com Will' },
    category: 'verb_tense',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.present_simple'],
    relatedTopics: ['grammar.future.going_to', 'grammar.conditionals.first', 'grammar.future_continuous.intro'],
    communicativeUses: [
      'Fazer previsões e prognósticos',
      'Decisões espontâneas tomadas no momento da fala',
      'Promessas e ofertas',
      'Fatos futuros certos',
    ],
    structures: {
      affirmative: ["Subject + will ('ll) + verb base"],
      negative: ["Subject + won't + verb base"],
      interrogative: ['Will + subject + verb base?'],
    },
    examples: [
      { en: "I'll call you back in five minutes.", ptBR: 'Te ligo em cinco minutos.', stage: 'guided_practice' },
      { en: "It won't take long.", ptBR: 'Não vai demorar muito.', stage: 'independent_production' },
      { en: 'Will you help me with this report?', ptBR: 'Você vai me ajudar com este relatório?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I will to go tomorrow.', correct: 'I will go tomorrow.', explanationPtBR: 'Depois de "will", use o verbo base sem "to".' },
    ],
    generationRules: {
      allowedContexts: ['previsões', 'promessas', 'decisões espontâneas', 'ofertas'],
      notesForGenerator: ['Contrastar com "going to". "Will" para decisões do momento; "going to" para planos já feitos.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['future', 'will', 'a2'],
    isActive: true,
  },
  {
    id: 'grammar.adjectives.comparative',
    version: 1,
    slug: 'comparative-adjectives',
    title: { en: 'Comparative Adjectives', ptBR: 'Adjetivos Comparativos' },
    category: 'adjective',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.present_simple'],
    relatedTopics: ['grammar.adjectives.superlative', 'grammar.present_simple'],
    communicativeUses: [
      'Comparar duas pessoas, coisas ou situações',
      'Expressar diferenças e semelhanças',
      'Argumentar preferências',
    ],
    structures: {
      affirmative: [
        'Short adjectives: adjective + -er + than (faster than, bigger than)',
        'Long adjectives: more + adjective + than (more interesting than)',
        'Irregular: better than, worse than, further than',
      ],
    },
    examples: [
      { en: 'Working from home is more comfortable than commuting.', ptBR: 'Trabalhar em casa é mais confortável do que se deslocar.', stage: 'guided_practice' },
      { en: 'This project is more complex than the previous one.', ptBR: 'Este projeto é mais complexo que o anterior.', stage: 'independent_production' },
      { en: 'I feel much better today.', ptBR: 'Me sinto muito melhor hoje.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'She is more tall than me.', correct: 'She is taller than me.', explanationPtBR: 'Adjetivos curtos (1-2 sílabas) usam -er, não "more".' },
      { incorrect: 'He is more better.', correct: 'He is better.', explanationPtBR: '"Better" já é a forma comparativa. Não use "more" com formas irregulares.' },
    ],
    generationRules: {
      allowedContexts: ['comparações de produtos', 'trabalho', 'estilo de vida'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['adjectives', 'comparative', 'a2'],
    isActive: true,
  },
  {
    id: 'grammar.adjectives.superlative',
    version: 1,
    slug: 'superlative-adjectives',
    title: { en: 'Superlative Adjectives', ptBR: 'Adjetivos Superlativos' },
    category: 'adjective',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.adjectives.comparative'],
    relatedTopics: ['grammar.adjectives.comparative'],
    communicativeUses: [
      'Identificar o grau máximo de uma qualidade dentro de um grupo',
      'Fazer recomendações e avaliações',
    ],
    structures: {
      affirmative: [
        'Short adjectives: the + adjective + -est (the fastest)',
        'Long adjectives: the most + adjective (the most interesting)',
        'Irregular: the best, the worst, the furthest',
      ],
    },
    examples: [
      { en: "It's the most challenging project I've worked on.", ptBR: 'É o projeto mais desafiador em que já trabalhei.', stage: 'guided_practice' },
      { en: "She's the best manager in the company.", ptBR: 'Ela é a melhor gestora da empresa.', stage: 'independent_production' },
      { en: 'This is the cheapest option available.', ptBR: 'Esta é a opção mais barata disponível.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'the most tall', correct: 'the tallest', explanationPtBR: 'Adjetivos curtos usam the + -est, não "the most".' },
    ],
    generationRules: {
      allowedContexts: ['recomendações', 'avaliações', 'rankings'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['adjectives', 'superlative', 'a2'],
    isActive: true,
  },
  {
    id: 'grammar.modals.should',
    version: 1,
    slug: 'should-shouldnt',
    title: { en: "Should / Shouldn't", ptBR: "Should / Shouldn't (Conselho)" },
    category: 'modal',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.present_simple'],
    relatedTopics: ['grammar.can', 'grammar.modals.must_have_to', 'grammar.modals.may_might'],
    communicativeUses: [
      'Dar conselhos e recomendações',
      'Expressar obrigação moral suave',
      'Fazer sugestões',
      'Criticar comportamento passado (should have)',
    ],
    structures: {
      affirmative: ['Subject + should + verb base'],
      negative: ["Subject + shouldn't + verb base"],
      interrogative: ['Should + subject + verb base?'],
    },
    examples: [
      { en: 'You should drink more water.', ptBR: 'Você deveria beber mais água.', stage: 'guided_practice' },
      { en: "We shouldn't ignore this problem.", ptBR: 'Não deveríamos ignorar esse problema.', stage: 'independent_production' },
      { en: 'Should I send the email now?', ptBR: 'Devo enviar o e-mail agora?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'You should to go.', correct: 'You should go.', explanationPtBR: 'Depois de "should", use o verbo base sem "to".' },
    ],
    generationRules: {
      allowedContexts: ['conselhos de saúde', 'work-life balance', 'situações de decisão'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['modal', 'should', 'advice', 'a2'],
    isActive: true,
  },
  {
    id: 'grammar.modals.must_have_to',
    version: 1,
    slug: 'must-have-to',
    title: { en: 'Must / Have To (Obligation)', ptBR: 'Must / Have To (Obrigação)' },
    category: 'modal',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.present_simple', 'grammar.modals.should'],
    relatedTopics: ['grammar.modals.should', 'grammar.modals.deduction', 'grammar.negation.basic'],
    communicativeUses: [
      'Expressar obrigação interna ou pessoal (must)',
      'Expressar obrigação externa ou regra (have to)',
      'Expressar necessidade',
      'Proibição (must not)',
    ],
    structures: {
      affirmative: ['Subject + must + verb base', 'Subject + have/has to + verb base'],
      negative: ["Subject + mustn't + verb base (prohibition)", "Subject + don't/doesn't have to + verb base (no obligation)"],
      interrogative: ['Do/Does + subject + have to + verb base?'],
    },
    examples: [
      { en: 'I must finish this report today.', ptBR: 'Eu preciso terminar este relatório hoje.', stage: 'guided_practice' },
      { en: 'You have to wear a badge in the building.', ptBR: 'Você tem que usar crachá no prédio.', stage: 'independent_production' },
      { en: "We don't have to work on Sundays.", ptBR: 'Não precisamos trabalhar aos domingos.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: "You don't must do this.", correct: "You don't have to do this.", explanationPtBR: '"Must" não forma negativa com "don\'t". Use "don\'t have to" para "não é necessário".' },
    ],
    generationRules: {
      allowedContexts: ['regras de trabalho', 'obrigações do dia a dia', 'necessidades pessoais'],
      notesForGenerator: ["Distinguir 'mustn't' (proibido) de 'don't have to' (não é necessário)."],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['modal', 'must', 'have_to', 'obligation', 'a2'],
    isActive: true,
  },
  {
    id: 'grammar.modals.may_might',
    version: 1,
    slug: 'may-might',
    title: { en: 'May / Might (Introductory)', ptBR: 'May / Might (Possibilidade — Introdução)' },
    category: 'modal',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.modals.should'],
    relatedTopics: ['grammar.modals.should', 'grammar.modals.deduction', 'grammar.hedging.basic'],
    communicativeUses: [
      'Expressar possibilidade presente ou futura',
      'Exprimir incerteza',
      'Dar permissão formal (may)',
    ],
    structures: {
      affirmative: ['Subject + may/might + verb base'],
      negative: ["Subject + may not/might not + verb base"],
    },
    examples: [
      { en: "I might work from home tomorrow.", ptBR: 'Posso vir a trabalhar de casa amanhã.', stage: 'guided_practice' },
      { en: 'She may not come to the party.', ptBR: 'Ela pode não vir à festa.', stage: 'independent_production' },
      { en: 'It might rain this afternoon.', ptBR: 'Pode chover esta tarde.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'She might to arrive late.', correct: 'She might arrive late.', explanationPtBR: 'Depois de "might/may", use o verbo base sem "to".' },
    ],
    generationRules: {
      allowedContexts: ['previsões incertas', 'planos tentaivos', 'situações de dúvida'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['modal', 'may', 'might', 'possibility', 'a2'],
    isActive: true,
  },
  {
    id: 'grammar.present_perfect.intro',
    version: 1,
    slug: 'present-perfect-intro',
    title: { en: 'Present Perfect (Introductory)', ptBR: 'Present Perfect (Introdução)' },
    category: 'verb_tense',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.past_simple', 'grammar.verb_to_be.present'],
    relatedTopics: ['grammar.present_perfect.vs_past_simple', 'grammar.present_perfect.markers', 'grammar.present_perfect_continuous.intro'],
    communicativeUses: [
      'Falar sobre experiências de vida sem tempo específico',
      'Descrever ações passadas com relevância no presente',
      'Expressar mudanças ao longo do tempo',
    ],
    structures: {
      affirmative: ["Subject + have/has + past participle"],
      negative: ["Subject + haven't/hasn't + past participle"],
      interrogative: ['Have/Has + subject + past participle?'],
    },
    examples: [
      { en: "I've worked in three different countries.", ptBR: 'Já trabalhei em três países diferentes.', stage: 'guided_practice' },
      { en: "She hasn't visited London yet.", ptBR: 'Ela ainda não visitou Londres.', stage: 'independent_production' },
      { en: 'Have you ever tried Japanese food?', ptBR: 'Você já experimentou comida japonesa?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I have went there.', correct: 'I have gone there.', explanationPtBR: 'Use o particípio passado. "Go" → "gone", não "went".' },
      { incorrect: 'I have seen him yesterday.', correct: 'I saw him yesterday.', explanationPtBR: 'Com tempo específico (yesterday), use Past Simple, não Present Perfect.' },
    ],
    generationRules: {
      allowedContexts: ['experiências de vida', 'conquistas profissionais', 'notícias recentes'],
      notesForGenerator: ['Um dos tópicos mais desafiadores para falantes de português. Reforçar diferença com Past Simple.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 15,
      requiredContextsForMastery: 3,
    },
    tags: ['present_perfect', 'a2', 'high_frequency', 'persistent_challenge'],
    isActive: true,
  },
  {
    id: 'grammar.present_perfect.markers',
    version: 1,
    slug: 'present-perfect-markers',
    title: { en: 'Present Perfect Markers (ever, never, just, already, yet)', ptBR: 'Marcadores do Present Perfect (ever, never, just, already, yet)' },
    category: 'verb_tense',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.present_perfect.intro'],
    relatedTopics: ['grammar.present_perfect.intro', 'grammar.present_perfect.vs_past_simple'],
    communicativeUses: [
      'Falar sobre experiências com "ever" e "never"',
      'Indicar ação recente com "just"',
      'Indicar ação já concluída com "already"',
      'Indicar algo ainda não feito com "yet"',
    ],
    structures: {
      affirmative: ['Subject + have/has + just/already + past participle'],
      negative: ["Subject + haven't/hasn't + past participle + yet"],
      interrogative: ['Have/Has + subject + ever + past participle?'],
    },
    examples: [
      { en: "I've just sent the email.", ptBR: 'Acabei de enviar o e-mail.', stage: 'guided_practice' },
      { en: "She hasn't finished the project yet.", ptBR: 'Ela ainda não terminou o projeto.', stage: 'independent_production' },
      { en: 'Have you ever been to Japan?', ptBR: 'Você já foi ao Japão?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I already have eaten.', correct: "I've already eaten.", explanationPtBR: '"Already" vem depois do auxiliar have/has.' },
      { incorrect: "I haven't eaten yet not.", correct: "I haven't eaten yet.", explanationPtBR: '"Yet" vai no final da frase negativa.' },
    ],
    generationRules: {
      allowedContexts: ['notícias recentes', 'experiências de vida', 'atualizações de progresso'],
    },
    assessment: {
      opportunityTypes: ['gap_fill', 'sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['present_perfect', 'markers', 'a2', 'b1'],
    isActive: true,
  },
  {
    id: 'grammar.infinitive.of_purpose',
    version: 1,
    slug: 'infinitive-of-purpose',
    title: { en: 'Infinitive of Purpose (to + verb)', ptBR: 'Infinitivo de Propósito (to + verbo)' },
    category: 'verb_form',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.present_simple'],
    relatedTopics: ['grammar.gerunds.basic', 'grammar.gerund_infinitive.choice'],
    communicativeUses: [
      'Expressar objetivo ou propósito de uma ação',
      'Explicar por que alguém faz algo',
    ],
    structures: {
      affirmative: ['Subject + verb + to + verb base (to express purpose)', 'in order to + verb base (more formal)'],
    },
    examples: [
      { en: 'I go to the gym to stay healthy.', ptBR: 'Vou à academia para ficar saudável.', stage: 'guided_practice' },
      { en: "She studied English to get a better job.", ptBR: 'Ela estudou inglês para conseguir um emprego melhor.', stage: 'independent_production' },
      { en: 'He called to ask about the schedule.', ptBR: 'Ele ligou para perguntar sobre a agenda.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I went there for buy food.', correct: 'I went there to buy food.', explanationPtBR: 'Para expressar propósito, use "to + verbo", não "for + verbo".' },
    ],
    generationRules: {
      allowedContexts: ['motivações', 'objetivos', 'explicações de propósito'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 8,
    },
    tags: ['infinitive', 'purpose', 'a2'],
    isActive: true,
  },
  {
    id: 'grammar.gerunds.basic',
    version: 1,
    slug: 'gerunds-basic',
    title: { en: 'Gerunds (Basic: verb + -ing as noun)', ptBR: 'Gerúndio (Básico: verbo + -ing como substantivo)' },
    category: 'verb_form',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.present_continuous'],
    relatedTopics: ['grammar.infinitive.of_purpose', 'grammar.gerund_infinitive.choice', 'grammar.present_continuous'],
    communicativeUses: [
      'Usar um verbo como sujeito de uma frase',
      'Usar um verbo como objeto de certos verbos (enjoy, love, hate, mind)',
      'Falar sobre atividades de forma geral',
    ],
    structures: {
      affirmative: [
        'Gerund as subject: Swimming is great exercise.',
        'Gerund as object: I enjoy reading.',
        'After prepositions: She is good at cooking.',
      ],
    },
    examples: [
      { en: 'Reading in English every day helps a lot.', ptBR: 'Ler em inglês todos os dias ajuda muito.', stage: 'guided_practice' },
      { en: 'I enjoy working with international teams.', ptBR: 'Gosto de trabalhar com equipes internacionais.', stage: 'independent_production' },
      { en: "She's not interested in joining the project.", ptBR: 'Ela não está interessada em participar do projeto.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I enjoy to read.', correct: 'I enjoy reading.', explanationPtBR: '"Enjoy" é seguido de gerúndio (-ing), não de infinitivo.' },
    ],
    generationRules: {
      allowedContexts: ['hobbies', 'preferências', 'habilidades'],
      notesForGenerator: ['Focar em verbos comuns seguidos de gerúndio: enjoy, love, hate, mind, avoid, finish, keep.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['gerunds', 'a2', 'verb_patterns'],
    isActive: true,
  },
  {
    id: 'grammar.conditionals.zero',
    version: 1,
    slug: 'zero-conditional',
    title: { en: 'Zero Conditional', ptBR: 'Condicional Zero (Fatos e Verdades Gerais)' },
    category: 'conditional',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.present_simple'],
    relatedTopics: ['grammar.present_simple', 'grammar.conditionals.first'],
    communicativeUses: [
      'Expressar fatos científicos e verdades gerais',
      'Descrever situações que sempre produzem o mesmo resultado',
      'Dar instruções sobre condições',
    ],
    structures: {
      affirmative: ['If + present simple, + present simple'],
      other: ['When + present simple, + present simple (equivalent meaning)'],
    },
    examples: [
      { en: 'If you heat water to 100°C, it boils.', ptBR: 'Se você aquecer a água a 100°C, ela ferve.', stage: 'guided_practice' },
      { en: 'Plants die if they get no water.', ptBR: 'As plantas morrem se não recebem água.', stage: 'independent_production' },
      { en: "If I'm stressed, I usually go for a walk.", ptBR: 'Se estou estressado, costumo sair para caminhar.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'If you will heat water, it boils.', correct: 'If you heat water, it boils.', explanationPtBR: 'No zero conditional, ambas as partes usam present simple. Não use "will" após "if".' },
    ],
    generationRules: {
      allowedContexts: ['fatos científicos', 'hábitos condicionais', 'instruções'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 8,
    },
    tags: ['conditional', 'zero_conditional', 'a2'],
    isActive: true,
  },
  {
    id: 'grammar.conditionals.first',
    version: 1,
    slug: 'first-conditional',
    title: { en: 'First Conditional', ptBR: 'Primeiro Condicional (Situações Reais)' },
    category: 'conditional',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'A2',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.present_simple', 'grammar.future.will'],
    relatedTopics: ['grammar.conditionals.zero', 'grammar.conditionals.second', 'grammar.future.will'],
    communicativeUses: [
      'Falar sobre situações reais ou possíveis e suas consequências',
      'Fazer promessas condicionais',
      'Expressar avisos e ameaças',
    ],
    structures: {
      affirmative: ['If + present simple, + will + verb base'],
      other: ['Unless + present simple, + will + verb base (negative condition)'],
    },
    examples: [
      { en: "If I get the promotion, I'll celebrate with the team.", ptBR: 'Se eu conseguir a promoção, vou comemorar com a equipe.', stage: 'guided_practice' },
      { en: "She won't accept the offer if the salary isn't good.", ptBR: 'Ela não aceitará a oferta se o salário não for bom.', stage: 'independent_production' },
      { en: "If you finish early, we'll leave together.", ptBR: 'Se você terminar cedo, vamos sair juntos.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'If I will finish, I will call.', correct: 'If I finish, I will call.', explanationPtBR: 'Não use "will" na cláusula com "if". Use present simple.' },
    ],
    generationRules: {
      allowedContexts: ['planejamento', 'negociações', 'situações condicionais reais'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['conditional', 'first_conditional', 'a2'],
    isActive: true,
  },
  {
    id: 'grammar.relative_clauses.basic',
    version: 1,
    slug: 'relative-clauses-basic',
    title: { en: 'Relative Clauses (Basic: who, which, that)', ptBR: 'Orações Relativas Básicas (who, which, that)' },
    category: 'relative_clause',
    minimumExposureLevel: 'A2',
    minimumGuidedPracticeLevel: 'A2',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B1',
    prerequisites: ['grammar.present_simple', 'grammar.questions.basic'],
    relatedTopics: ['grammar.relative_clauses.defining', 'grammar.relative_clauses.non_defining'],
    communicativeUses: [
      'Dar informações adicionais sobre pessoas ou coisas',
      'Definir e identificar quem ou o que está sendo discutido',
      'Combinar frases simples em frases mais complexas',
    ],
    structures: {
      affirmative: [
        'who/that + clause (for people)',
        'which/that + clause (for things)',
      ],
    },
    examples: [
      { en: 'The person who helped me is my manager.', ptBR: 'A pessoa que me ajudou é o meu gerente.', stage: 'guided_practice' },
      { en: 'The project that we finished was very complex.', ptBR: 'O projeto que terminamos foi muito complexo.', stage: 'independent_production' },
      { en: "The book which she recommended is excellent.", ptBR: 'O livro que ela recomendou é excelente.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'The person which helped me...', correct: 'The person who helped me...', explanationPtBR: 'Use "who" para pessoas e "which" para coisas.' },
    ],
    generationRules: {
      allowedContexts: ['descrições de pessoas', 'descrições de objetos/situações'],
      notesForGenerator: ['Começar com defining relative clauses. Não introduzir non-defining ainda.'],
    },
    assessment: {
      opportunityTypes: ['sentence_combination', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['relative_clauses', 'a2', 'complex_sentences'],
    isActive: true,
  },
] as const satisfies readonly GrammarTopic[];
