import { GrammarTopic } from '../grammar-types';

export const B1_TOPICS: readonly GrammarTopic[] = [
  {
    id: 'grammar.present_perfect.vs_past_simple',
    version: 1,
    slug: 'present-perfect-vs-past-simple',
    title: { en: 'Present Perfect vs Past Simple', ptBR: 'Present Perfect vs. Passado Simples' },
    category: 'verb_tense',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.present_perfect.intro', 'grammar.past_simple'],
    relatedTopics: ['grammar.present_perfect.intro', 'grammar.past_simple', 'grammar.present_perfect.markers'],
    communicativeUses: [
      'Distinguir experiências sem tempo definido (present perfect) de eventos em momento específico (past simple)',
      'Falar com precisão sobre o passado em contextos formais',
      'Narrar e relatar eventos com nuance temporal',
    ],
    structures: {
      affirmative: [
        'Present perfect: Have/Has + past participle (experience, unfinished time)',
        'Past simple: Subject + verb-ed/irregular (finished time, specific moment)',
      ],
      other: [
        'Triggers for present perfect: ever, never, just, already, yet, recently, so far',
        'Triggers for past simple: yesterday, last week, in 2020, ago, when',
      ],
    },
    examples: [
      { en: "I've visited Paris three times. I went there last summer.", ptBR: 'Já visitei Paris três vezes. Fui lá no verão passado.', stage: 'guided_practice' },
      { en: "Have you tried the new restaurant? I went there on Friday.", ptBR: 'Você já foi ao novo restaurante? Eu fui lá na sexta.', stage: 'independent_production' },
      { en: "She's worked here for years. She started in 2018.", ptBR: 'Ela trabalha aqui há anos. Começou em 2018.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I have seen him yesterday.', correct: 'I saw him yesterday.', explanationPtBR: '"Yesterday" é um marcador de tempo específico — use Past Simple.' },
      { incorrect: 'Did you ever try sushi?', correct: 'Have you ever tried sushi?', explanationPtBR: '"Ever" com experiências de vida usa Present Perfect.' },
    ],
    generationRules: {
      allowedContexts: ['conversas sobre experiências', 'entrevistas', 'narrativas pessoais'],
      notesForGenerator: ['Ponto de maior confusão para brasileiros. Criar missões que forçam a escolha consciente.'],
    },
    assessment: {
      opportunityTypes: ['error_correction', 'gap_fill', 'free_production'],
      evidenceRequiredForMastery: 20,
      requiredContextsForMastery: 4,
    },
    tags: ['present_perfect', 'past_simple', 'b1', 'contrast', 'persistent_challenge'],
    isActive: true,
  },
  {
    id: 'grammar.present_perfect_continuous.intro',
    version: 1,
    slug: 'present-perfect-continuous',
    title: { en: 'Present Perfect Continuous', ptBR: 'Present Perfect Continuous' },
    category: 'verb_tense',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.present_perfect.intro', 'grammar.present_continuous'],
    relatedTopics: ['grammar.present_perfect.intro', 'grammar.past_perfect.intro'],
    communicativeUses: [
      'Descrever ação que começou no passado e continua agora',
      'Enfatizar a duração de uma atividade em andamento',
      'Explicar um estado presente com causa passada',
    ],
    structures: {
      affirmative: ["Subject + have/has + been + verb-ing"],
      negative: ["Subject + haven't/hasn't + been + verb-ing"],
      interrogative: ['How long + have/has + subject + been + verb-ing?'],
    },
    examples: [
      { en: "I've been working on this project for three months.", ptBR: 'Estou trabalhando neste projeto há três meses.', stage: 'guided_practice' },
      { en: "She's been studying English for two years.", ptBR: 'Ela está estudando inglês há dois anos.', stage: 'independent_production' },
      { en: 'How long have you been living in São Paulo?', ptBR: 'Há quanto tempo você mora em São Paulo?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I have been work here since 2020.', correct: 'I have been working here since 2020.', explanationPtBR: 'O Present Perfect Continuous usa "been + verb-ing".' },
    ],
    generationRules: {
      allowedContexts: ['duração de atividades', 'rotinas estabelecidas', 'resultados visíveis de ações'],
      notesForGenerator: ['Frequentemente usado com "for" (duração) e "since" (ponto de início).'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['present_perfect_continuous', 'b1', 'duration'],
    isActive: true,
  },
  {
    id: 'grammar.past_perfect.intro',
    version: 1,
    slug: 'past-perfect-intro',
    title: { en: 'Past Perfect (Introductory)', ptBR: 'Past Perfect — Mais-que-perfeito (Introdução)' },
    category: 'verb_tense',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.past_simple', 'grammar.present_perfect.intro'],
    relatedTopics: ['grammar.past_simple', 'grammar.narrative_tenses', 'grammar.past_perfect.independent'],
    communicativeUses: [
      'Descrever ação que aconteceu antes de outra ação passada',
      'Criar clareza temporal em narrativas',
      'Expressar causa e efeito no passado',
    ],
    structures: {
      affirmative: ['Subject + had + past participle'],
      negative: ["Subject + hadn't + past participle"],
      interrogative: ['Had + subject + past participle?'],
    },
    examples: [
      { en: "When I arrived, the meeting had already started.", ptBR: 'Quando cheguei, a reunião já havia começado.', stage: 'guided_practice' },
      { en: "She got the job because she had prepared well.", ptBR: 'Ela conseguiu o emprego porque havia se preparado bem.', stage: 'independent_production' },
      { en: "I was tired because I hadn't slept well.", ptBR: 'Eu estava cansado porque não havia dormido bem.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'When she arrived, I already left.', correct: 'When she arrived, I had already left.', explanationPtBR: 'Use Past Perfect para a ação que aconteceu primeiro na sequência do passado.' },
    ],
    generationRules: {
      allowedContexts: ['narrativas sequenciais', 'explicações de causa no passado'],
      notesForGenerator: ['Introduzir em par com Past Simple para criar contraste claro de sequência temporal.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'narrative_writing', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['past_perfect', 'b1', 'narrative', 'sequence'],
    isActive: true,
  },
  {
    id: 'grammar.future_continuous.intro',
    version: 1,
    slug: 'future-continuous-intro',
    title: { en: 'Future Continuous (Introductory)', ptBR: 'Futuro Contínuo (Introdução)' },
    category: 'verb_tense',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.present_continuous', 'grammar.future.will'],
    relatedTopics: ['grammar.future.will', 'grammar.future_continuous'],
    communicativeUses: [
      'Descrever ação em andamento em um momento específico no futuro',
      'Fazer perguntas educadas sobre planos de alguém',
      'Indicar que algo vai acontecer como parte de uma rotina futura',
    ],
    structures: {
      affirmative: ["Subject + will be + verb-ing"],
      negative: ["Subject + won't be + verb-ing"],
      interrogative: ['Will + subject + be + verb-ing?'],
    },
    examples: [
      { en: 'This time tomorrow, I will be flying to London.', ptBR: 'A essa hora amanhã, estarei voando para Londres.', stage: 'guided_practice' },
      { en: "We won't be working next Monday — it's a holiday.", ptBR: 'Não estaremos trabalhando na próxima segunda — é feriado.', stage: 'independent_production' },
      { en: 'Will you be using the car tonight?', ptBR: 'Você vai estar usando o carro hoje à noite?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I will being working there.', correct: 'I will be working there.', explanationPtBR: 'O Future Continuous usa "will be + verb-ing", nunca "will being".' },
    ],
    generationRules: {
      allowedContexts: ['planos futuros específicos', 'perguntas educadas sobre disponibilidade'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['future_continuous', 'b1', 'future'],
    isActive: true,
  },
  {
    id: 'grammar.used_to',
    version: 1,
    slug: 'used-to',
    title: { en: 'Used To (Past Habits)', ptBR: 'Used To (Hábitos Passados)' },
    category: 'verb_form',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.past_simple'],
    relatedTopics: ['grammar.past_simple', 'grammar.would.past_habits'],
    communicativeUses: [
      'Falar sobre hábitos e estados que existiam no passado mas não mais',
      'Contrastar o passado com o presente',
      'Narrar mudanças de vida',
    ],
    structures: {
      affirmative: ['Subject + used to + verb base'],
      negative: ["Subject + didn't use to + verb base"],
      interrogative: ['Did + subject + use to + verb base?'],
    },
    examples: [
      { en: 'I used to work in an office, but now I work from home.', ptBR: 'Eu costumava trabalhar em um escritório, mas agora trabalho em casa.', stage: 'guided_practice' },
      { en: "She didn't use to enjoy public speaking.", ptBR: 'Ela não costumava gostar de falar em público.', stage: 'independent_production' },
      { en: 'Did you use to play any sports as a child?', ptBR: 'Você costumava praticar algum esporte quando criança?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I use to go there.', correct: 'I used to go there.', explanationPtBR: '"Used to" sempre tem o "d" no final — é uma forma fixa no passado.' },
      { incorrect: "She didn't used to like it.", correct: "She didn't use to like it.", explanationPtBR: 'Com "didn\'t", use "use to" (sem o "d").' },
    ],
    generationRules: {
      allowedContexts: ['mudanças de vida', 'autobiografia', 'contraste passado/presente'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['used_to', 'past_habits', 'b1'],
    isActive: true,
  },
  {
    id: 'grammar.would.past_habits',
    version: 1,
    slug: 'would-past-habits',
    title: { en: 'Would for Past Habits', ptBR: 'Would para Hábitos Passados' },
    category: 'modal',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.past_simple', 'grammar.modals.should'],
    relatedTopics: ['grammar.used_to', 'grammar.past_simple'],
    communicativeUses: [
      'Descrever ações repetidas ou habituais no passado (não estados)',
      'Dar ênfase nostálgica a hábitos passados em narrativas',
    ],
    structures: {
      affirmative: ['Subject + would + verb base (for repeated past actions, not states)'],
      other: ['Note: Unlike "used to", "would" cannot be used for past states (e.g., NOT "I would be shy")'],
    },
    examples: [
      { en: 'As a child, I would spend summers at my grandparents\' house.', ptBR: 'Quando criança, eu passava os verões na casa dos meus avós.', stage: 'guided_practice' },
      { en: "Every morning, she would walk to the market and buy fresh bread.", ptBR: 'Toda manhã, ela ia ao mercado e comprava pão fresco.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I would be shy when I was young.', correct: 'I used to be shy when I was young.', explanationPtBR: '"Would" não pode ser usado para estados. Use "used to" para estados passados.' },
    ],
    generationRules: {
      allowedContexts: ['memórias', 'narrativas nostálgicas', 'histórias pessoais'],
      notesForGenerator: ['Ensinar em contraste com "used to". "Would" apenas para ações, não estados.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'narrative_writing'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['would', 'past_habits', 'b1', 'narrative'],
    isActive: true,
  },
  {
    id: 'grammar.conditionals.second',
    version: 1,
    slug: 'second-conditional',
    title: { en: 'Second Conditional', ptBR: 'Segundo Condicional (Situações Hipotéticas)' },
    category: 'conditional',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.past_simple', 'grammar.modals.should', 'grammar.conditionals.first'],
    relatedTopics: ['grammar.conditionals.first', 'grammar.conditionals.third', 'grammar.wish_if_only'],
    communicativeUses: [
      'Falar sobre situações hipotéticas ou improváveis no presente/futuro',
      'Dar conselhos através de hipóteses ("If I were you...")',
      'Imaginar cenários alternativos',
    ],
    structures: {
      affirmative: ['If + past simple, + would + verb base'],
      other: ["Note: 'were' is used for all persons in formal/written use (If I were...)"],
    },
    examples: [
      { en: 'If I had more time, I would learn a new language.', ptBR: 'Se eu tivesse mais tempo, aprenderia um novo idioma.', stage: 'guided_practice' },
      { en: "If I were you, I wouldn't accept that offer.", ptBR: 'Se eu fosse você, não aceitaria essa oferta.', stage: 'independent_production' },
      { en: 'What would you do if you lost your job?', ptBR: 'O que você faria se perdesse seu emprego?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'If I would have money, I would travel.', correct: 'If I had money, I would travel.', explanationPtBR: 'Não use "would" na cláusula com "if". Use Past Simple.' },
    ],
    generationRules: {
      allowedContexts: ['cenários hipotéticos', 'conselhos', 'sonhos e aspirações'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 15,
    },
    tags: ['conditional', 'second_conditional', 'b1', 'hypothetical'],
    isActive: true,
  },
  {
    id: 'grammar.passive.present_simple',
    version: 1,
    slug: 'passive-present-simple',
    title: { en: 'Passive Voice (Present Simple)', ptBR: 'Voz Passiva (Presente Simples)' },
    category: 'passive',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.verb_to_be.present', 'grammar.present_simple'],
    relatedTopics: ['grammar.passive.multi_tense', 'grammar.causative'],
    communicativeUses: [
      'Focar na ação ou no resultado, não no agente',
      'Escrever sobre processos e procedimentos',
      'Linguagem formal e impessoal',
      'Quando o agente é desconhecido ou óbvio',
    ],
    structures: {
      affirmative: ['Subject + is/are + past participle (+ by agent)'],
      negative: ["Subject + isn't/aren't + past participle"],
      interrogative: ['Is/Are + subject + past participle?'],
    },
    examples: [
      { en: 'The report is reviewed every Monday.', ptBR: 'O relatório é revisado toda segunda-feira.', stage: 'guided_practice' },
      { en: 'English is spoken in over 50 countries.', ptBR: 'O inglês é falado em mais de 50 países.', stage: 'independent_production' },
      { en: "New employees are trained by the HR team.", ptBR: 'Novos funcionários são treinados pela equipe de RH.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'The book is write by her.', correct: 'The book is written by her.', explanationPtBR: 'A voz passiva usa o particípio passado, não o infinitivo.' },
    ],
    generationRules: {
      allowedContexts: ['processos corporativos', 'descrições de produtos', 'notícias', 'ciência'],
      notesForGenerator: ['Focar primeiro no presente simples passivo. Expandir para outros tempos em B2.'],
    },
    assessment: {
      opportunityTypes: ['sentence_transformation', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['passive', 'b1', 'formal_writing'],
    isActive: true,
  },
  {
    id: 'grammar.reported_speech.basic',
    version: 1,
    slug: 'reported-speech-basic',
    title: { en: 'Reported Speech (Basic)', ptBR: 'Discurso Indireto (Básico)' },
    category: 'reported_speech',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.past_simple', 'grammar.present_simple', 'grammar.questions.basic'],
    relatedTopics: ['grammar.past_simple', 'grammar.reported_speech.advanced'],
    communicativeUses: [
      'Relatar o que alguém disse',
      'Transmitir mensagens e informações de terceiros',
      'Escrever atas de reuniões e resumos',
    ],
    structures: {
      affirmative: ['Subject + said (that) + reported clause (with backshift)'],
      other: [
        'Present → Past: "I am" → He said he was',
        'Past → Past perfect: "I went" → She said she had gone',
        'Will → Would: "I will" → They said they would',
      ],
    },
    examples: [
      { en: '"I work from home." → She said she worked from home.', ptBR: '"Trabalho em casa." → Ela disse que trabalhava em casa.', stage: 'guided_practice' },
      { en: '"We will call you." → They said they would call me.', ptBR: '"Vamos te ligar." → Eles disseram que me ligariam.', stage: 'independent_production' },
      { en: '"I am tired." → He said he was tired.', ptBR: '"Estou cansado." → Ele disse que estava cansado.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: "She said she is tired.", correct: 'She said she was tired.', explanationPtBR: 'No discurso indireto, o tempo verbal recua (backshift): "is" → "was".' },
    ],
    generationRules: {
      allowedContexts: ['relatar conversas', 'transmitir informações', 'atas de reunião'],
      notesForGenerator: ['Começar com declarações simples antes de perguntas e imperativas no discurso indireto.'],
    },
    assessment: {
      opportunityTypes: ['sentence_transformation', 'free_production'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['reported_speech', 'b1', 'backshift'],
    isActive: true,
  },
  {
    id: 'grammar.modals.deduction',
    version: 1,
    slug: 'modals-deduction',
    title: { en: 'Modal Verbs for Deduction (must, can\'t, might)', ptBR: 'Modais de Dedução (must, can\'t, might)' },
    category: 'modal',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.modals.may_might', 'grammar.modals.must_have_to'],
    relatedTopics: ['grammar.modals.may_might', 'grammar.modals.past', 'grammar.hedging.basic'],
    communicativeUses: [
      'Fazer deduções sobre o presente baseadas em evidências',
      'Expressar certeza relativa sobre situações',
      'Especular sobre causas e situações',
    ],
    structures: {
      affirmative: [
        'must + verb base (near certainty: positive)',
        "can't + verb base (near certainty: negative)",
        'might/may + verb base (possibility)',
      ],
    },
    examples: [
      { en: "She must be the new manager — everyone is calling her for decisions.", ptBR: 'Ela deve ser a nova gestora — todo mundo a chama para decisões.', stage: 'guided_practice' },
      { en: "He can't be at home — his car isn't there.", ptBR: 'Ele não pode estar em casa — o carro dele não está lá.', stage: 'independent_production' },
      { en: "They might be running late — the traffic is terrible.", ptBR: 'Eles devem estar atrasados — o trânsito está terrível.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'He must to be tired.', correct: 'He must be tired.', explanationPtBR: 'Depois de "must" (modal), use o verbo base sem "to".' },
    ],
    generationRules: {
      allowedContexts: ['situações de inferência', 'discussões sobre comportamento', 'deduções lógicas'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['modal', 'deduction', 'b1', 'certainty'],
    isActive: true,
  },
  {
    id: 'grammar.gerund_infinitive.choice',
    version: 1,
    slug: 'gerund-infinitive-choice',
    title: { en: 'Gerund vs Infinitive Choice', ptBR: 'Gerúndio vs. Infinitivo — Escolha' },
    category: 'verb_form',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.gerunds.basic', 'grammar.infinitive.of_purpose'],
    relatedTopics: ['grammar.gerunds.basic', 'grammar.infinitive.of_purpose'],
    communicativeUses: [
      'Combinar verbos corretamente (verbs followed by gerund or infinitive)',
      'Expressar mudança de significado (stop, remember, try + gerund vs infinitive)',
    ],
    structures: {
      affirmative: [
        'Gerund after: enjoy, avoid, mind, finish, consider, suggest, keep, deny',
        'Infinitive after: want, need, decide, hope, plan, expect, agree, refuse',
        'Both (different meaning): stop, remember, try, forget',
      ],
    },
    examples: [
      { en: 'I stopped smoking three years ago.  /  I stopped to smoke (took a break to smoke).', ptBR: 'Parei de fumar há três anos.  /  Parei para fumar.', stage: 'guided_practice' },
      { en: 'She decided to apply for the position.', ptBR: 'Ela decidiu se candidatar para o cargo.', stage: 'independent_production' },
      { en: 'He avoided making eye contact during the presentation.', ptBR: 'Ele evitou fazer contato visual durante a apresentação.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I enjoy to work late.', correct: 'I enjoy working late.', explanationPtBR: '"Enjoy" é sempre seguido de gerúndio (-ing).' },
    ],
    generationRules: {
      allowedContexts: ['preferências', 'decisões', 'hábitos'],
      notesForGenerator: ['Verbs with meaning change (stop, remember, try) são prioridade de ensino.'],
    },
    assessment: {
      opportunityTypes: ['gap_fill', 'error_correction', 'free_production'],
      evidenceRequiredForMastery: 15,
    },
    tags: ['gerund', 'infinitive', 'b1', 'verb_patterns'],
    isActive: true,
  },
  {
    id: 'grammar.relative_clauses.defining',
    version: 1,
    slug: 'relative-clauses-defining',
    title: { en: 'Defining Relative Clauses', ptBR: 'Orações Relativas Definidoras' },
    category: 'relative_clause',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.relative_clauses.basic'],
    relatedTopics: ['grammar.relative_clauses.basic', 'grammar.relative_clauses.non_defining'],
    communicativeUses: [
      'Identificar e definir pessoas ou coisas de forma específica',
      'Dar informação essencial para compreensão da frase',
      'Escrever definições precisas',
    ],
    structures: {
      affirmative: [
        'who/that (people as subject)',
        'whom/that/who (people as object — omittable)',
        'which/that (things — that omittable when object)',
        'whose (possession)',
        'where (place)',
        'when (time)',
      ],
    },
    examples: [
      { en: 'The company that hired her has offices worldwide.', ptBR: 'A empresa que a contratou tem escritórios no mundo todo.', stage: 'guided_practice' },
      { en: 'The colleague whose work I admire just got promoted.', ptBR: 'O colega cujo trabalho admiro acabou de ser promovido.', stage: 'independent_production' },
      { en: 'I remember the day when I got my first job.', ptBR: 'Lembro do dia em que consegui meu primeiro emprego.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'The person which called me was my boss.', correct: 'The person who called me was my boss.', explanationPtBR: 'Use "who" para pessoas, "which" para coisas.' },
    ],
    generationRules: {
      allowedContexts: ['descrições profissionais', 'definições', 'narrativas'],
    },
    assessment: {
      opportunityTypes: ['sentence_combination', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['relative_clauses', 'b1', 'defining'],
    isActive: true,
  },
  {
    id: 'grammar.question_tags',
    version: 1,
    slug: 'question-tags',
    title: { en: 'Question Tags', ptBR: 'Question Tags (Confirmações)' },
    category: 'question',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.verb_to_be.present', 'grammar.present_simple', 'grammar.negation.basic'],
    relatedTopics: ['grammar.questions.basic', 'grammar.negation.basic'],
    communicativeUses: [
      'Confirmar informações já mencionadas',
      'Buscar concordância ou confirmação do interlocutor',
      'Soar mais natural e fluente em conversas',
    ],
    structures: {
      other: [
        'Affirmative statement + negative tag: "She works here, doesn\'t she?"',
        "Negative statement + positive tag: \"You don't smoke, do you?\"",
        'Special cases: "I am late, aren\'t I?", "Let\'s go, shall we?"',
      ],
    },
    examples: [
      { en: "It's a great project, isn't it?", ptBR: 'É um ótimo projeto, não é?', stage: 'guided_practice' },
      { en: "You haven't sent the email yet, have you?", ptBR: 'Você ainda não enviou o e-mail, enviou?', stage: 'independent_production' },
      { en: "They can help us, can't they?", ptBR: 'Eles podem nos ajudar, não podem?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: "She works here, isn't it?", correct: "She works here, doesn't she?", explanationPtBR: 'A question tag usa o mesmo auxiliar do enunciado principal.' },
    ],
    generationRules: {
      allowedContexts: ['conversas informais', 'confirmações em reuniões', 'interação social'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['question_tags', 'b1', 'confirmation'],
    isActive: true,
  },
  {
    id: 'grammar.phrasal_verbs.common',
    version: 1,
    slug: 'phrasal-verbs-common',
    title: { en: 'Common Phrasal Verbs', ptBR: 'Phrasal Verbs Comuns' },
    category: 'verb_form',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.present_simple', 'grammar.past_simple'],
    relatedTopics: ['grammar.idiomatic_control', 'grammar.present_simple'],
    communicativeUses: [
      'Soar mais natural e fluente em inglês falado e informal',
      'Compreender textos e conversas nativas',
      'Expressar ações cotidianas com mais precisão',
    ],
    structures: {
      affirmative: [
        'Separable: turn on/off, pick up, put down, set up, give up, look up',
        'Inseparable: look after, come across, run into, get along with',
        'Three-word: look forward to, put up with, come up with',
      ],
    },
    examples: [
      { en: 'I came across an interesting article about AI.', ptBR: 'Deparei com um artigo interessante sobre IA.', stage: 'guided_practice' },
      { en: "She gave up trying to fix the problem alone.", ptBR: 'Ela desistiu de tentar resolver o problema sozinha.', stage: 'independent_production' },
      { en: "I'm looking forward to the conference next week.", ptBR: 'Estou ansioso para a conferência da próxima semana.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I look forward to meet you.', correct: 'I look forward to meeting you.', explanationPtBR: '"Look forward to" é seguido de gerúndio (to = preposição).' },
    ],
    generationRules: {
      allowedContexts: ['conversas de trabalho', 'e-mails profissionais', 'narrativas cotidianas'],
      notesForGenerator: ['Focar nos 20-30 mais comuns do contexto profissional e cotidiano.'],
    },
    assessment: {
      opportunityTypes: ['gap_fill', 'free_production', 'multiple_choice'],
      evidenceRequiredForMastery: 20,
      requiredContextsForMastery: 3,
    },
    tags: ['phrasal_verbs', 'b1', 'fluency'],
    isActive: true,
  },
  {
    id: 'grammar.connectors.cause_contrast',
    version: 1,
    slug: 'connectors-cause-contrast',
    title: { en: 'Connectors: Cause and Contrast', ptBR: 'Conectivos de Causa e Contraste' },
    category: 'conjunction',
    minimumExposureLevel: 'B1',
    minimumGuidedPracticeLevel: 'B1',
    minimumIndependentProductionLevel: 'B1',
    expectedMasteryLevel: 'B2',
    prerequisites: ['grammar.present_simple', 'grammar.past_simple'],
    relatedTopics: ['grammar.discourse_markers.argumentation', 'grammar.concession_contrast'],
    communicativeUses: [
      'Expressar causas e razões com coerência',
      'Contrastar ideias de forma eficaz',
      'Dar coesão a textos e argumentos',
      'Conectar frases e parágrafos de forma lógica',
    ],
    structures: {
      affirmative: [
        'Cause: because, since, as, due to, owing to, because of',
        'Contrast: but, however, although, even though, despite, in spite of',
        'Result: so, therefore, as a result, consequently',
      ],
    },
    examples: [
      { en: "She got the promotion because she worked incredibly hard.", ptBR: 'Ela conseguiu a promoção porque trabalhou incrivelmente duro.', stage: 'guided_practice' },
      { en: "Although the project was challenging, we delivered on time.", ptBR: 'Embora o projeto fosse desafiador, entregamos no prazo.', stage: 'independent_production' },
      { en: "The meeting was cancelled. As a result, we had more time to prepare.", ptBR: 'A reunião foi cancelada. Como resultado, tivemos mais tempo para nos preparar.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'Despite she was tired, she continued.', correct: 'Despite being tired, she continued.', explanationPtBR: '"Despite" e "in spite of" são seguidos de substantivo ou gerúndio, não de cláusula.' },
    ],
    generationRules: {
      allowedContexts: ['argumentação', 'relatórios', 'e-mails profissionais', 'discussões'],
      notesForGenerator: ['Crucial para coerência textual. Trabalhar em conjunto com estrutura paragráfica.'],
    },
    assessment: {
      opportunityTypes: ['gap_fill', 'sentence_combination', 'free_production'],
      evidenceRequiredForMastery: 15,
    },
    tags: ['connectors', 'cause', 'contrast', 'b1', 'cohesion'],
    isActive: true,
  },
] as const satisfies readonly GrammarTopic[];
