import { GrammarTopic } from '../grammar-types';

export const B2_TOPICS: readonly GrammarTopic[] = [
  {
    id: 'grammar.past_perfect.independent',
    version: 1,
    slug: 'past-perfect-independent',
    title: { en: 'Past Perfect (Independent Use)', ptBR: 'Past Perfect — Uso Independente' },
    category: 'verb_tense',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.past_perfect.intro'],
    relatedTopics: ['grammar.narrative_tenses', 'grammar.reported_speech.advanced', 'grammar.conditionals.third'],
    communicativeUses: [
      'Usar past perfect com fluência em narrativas complexas',
      'Expressar condições não atendidas antes de outra ação passada',
      'Criar sequências temporais sofisticadas',
    ],
    structures: {
      affirmative: ['Subject + had + past participle (nuanced temporal sequencing)'],
      other: [
        'By the time + past simple, + past perfect (completion before deadline)',
        'No sooner + past perfect + than + past simple (immediate sequence)',
        'Hardly/Scarcely + past perfect + when + past simple',
      ],
    },
    examples: [
      { en: 'By the time the client arrived, we had prepared everything.', ptBR: 'Quando o cliente chegou, já tínhamos preparado tudo.', stage: 'guided_practice' },
      { en: 'No sooner had she submitted the report than the boss requested changes.', ptBR: 'Mal ela havia enviado o relatório, o chefe já solicitou mudanças.', stage: 'independent_production' },
      { en: 'Hardly had they started when the system crashed.', ptBR: 'Mal haviam começado quando o sistema travou.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'No sooner she had left than...', correct: 'No sooner had she left than...', explanationPtBR: 'Após "no sooner" no início da frase, ocorre inversão (had + subject).' },
    ],
    generationRules: {
      allowedContexts: ['narrativas formais', 'relatórios analíticos', 'apresentações profissionais'],
      notesForGenerator: ['Enfatizar o uso independente e estruturas com inversão.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'narrative_writing', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['past_perfect', 'b2', 'advanced_narrative'],
    isActive: true,
  },
  {
    id: 'grammar.future_perfect.intro',
    version: 1,
    slug: 'future-perfect',
    title: { en: 'Future Perfect', ptBR: 'Futuro Perfeito' },
    category: 'verb_tense',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.future.will', 'grammar.past_perfect.intro'],
    relatedTopics: ['grammar.future.will', 'grammar.future_continuous'],
    communicativeUses: [
      'Indicar que uma ação estará completa antes de um ponto no futuro',
      'Fazer projeções e estimativas com prazo definido',
      'Planejar com referência temporal precisa',
    ],
    structures: {
      affirmative: ["Subject + will have + past participle"],
      negative: ["Subject + won't have + past participle"],
      interrogative: ['Will + subject + have + past participle + by...?'],
    },
    examples: [
      { en: 'By Friday, I will have finished the entire project.', ptBR: 'Até sexta-feira, terei terminado todo o projeto.', stage: 'guided_practice' },
      { en: "She won't have reviewed the documents by noon.", ptBR: 'Ela não terá revisado os documentos até o meio-dia.', stage: 'independent_production' },
      { en: 'Will you have completed the training by next month?', ptBR: 'Você terá concluído o treinamento até o próximo mês?', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'By tomorrow, I will finished the work.', correct: 'By tomorrow, I will have finished the work.', explanationPtBR: 'O Future Perfect requer "will have + past participle".' },
    ],
    generationRules: {
      allowedContexts: ['prazos profissionais', 'planejamento de projetos', 'metas com deadline'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['future_perfect', 'b2', 'deadlines'],
    isActive: true,
  },
  {
    id: 'grammar.future_continuous',
    version: 1,
    slug: 'future-continuous',
    title: { en: 'Future Continuous (Full Use)', ptBR: 'Futuro Contínuo (Uso Completo)' },
    category: 'verb_tense',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.future_continuous.intro'],
    relatedTopics: ['grammar.future_perfect.intro', 'grammar.future.will'],
    communicativeUses: [
      'Descrever ações em progresso em momentos futuros específicos',
      'Perguntar sobre planos de forma indireta e educada',
      'Projetar tendências e situações futuras duradouras',
    ],
    structures: {
      affirmative: ["Subject + will be + verb-ing"],
      negative: ["Subject + won't be + verb-ing"],
      interrogative: ['Will + subject + be + verb-ing?'],
      other: ['Often with: at this time tomorrow, this time next week, in five years'],
    },
    examples: [
      { en: "In five years, I'll be leading my own department.", ptBR: 'Daqui a cinco anos, estarei liderando meu próprio departamento.', stage: 'guided_practice' },
      { en: "Will you be attending the global summit next quarter?", ptBR: 'Você estará participando do summit global no próximo trimestre?', stage: 'independent_production' },
      { en: "This time next week, we'll be presenting to the board.", ptBR: 'A essa hora da semana que vem, estaremos apresentando para a diretoria.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I will be work all weekend.', correct: 'I will be working all weekend.', explanationPtBR: 'O Future Continuous usa "will be + verb-ing".' },
    ],
    generationRules: {
      allowedContexts: ['projeções de carreira', 'planos de longo prazo', 'perguntas indiretas sobre disponibilidade'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['future_continuous', 'b2'],
    isActive: true,
  },
  {
    id: 'grammar.narrative_tenses',
    version: 1,
    slug: 'narrative-tenses',
    title: { en: 'Narrative Tenses', ptBR: 'Tempos Narrativos (Past Simple, Past Continuous, Past Perfect)' },
    category: 'verb_tense',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.past_simple', 'grammar.past_continuous', 'grammar.past_perfect.intro'],
    relatedTopics: ['grammar.past_perfect.independent', 'grammar.reported_speech.advanced'],
    communicativeUses: [
      'Contar histórias e narrativas complexas com precisão temporal',
      'Combinar múltiplos tempos passados com fluidez',
      'Criar tensão e contexto em narrativas escritas e orais',
    ],
    structures: {
      affirmative: [
        'Past perfect: background / earlier action (had done)',
        'Past continuous: background / ongoing action (was/were doing)',
        'Past simple: main events / sequence (did)',
      ],
    },
    examples: [
      { en: "By the time I arrived, she had already left, and everyone was talking about what had happened.", ptBR: 'Quando cheguei, ela já tinha ido embora e todos estavam falando sobre o que havia acontecido.', stage: 'guided_practice' },
      { en: "I was preparing the presentation when my boss called to say the client had cancelled.", ptBR: 'Eu estava preparando a apresentação quando meu chefe ligou para dizer que o cliente havia cancelado.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'While I prepared, she had arrived.', correct: 'While I was preparing, she arrived.', explanationPtBR: 'Use past continuous para a ação de fundo e past simple para a ação que interrompe.' },
    ],
    generationRules: {
      allowedContexts: ['anedotas profissionais', 'histórias pessoais', 'estudos de caso narrativos'],
      notesForGenerator: ['Missões de narrativa longa são ideais para praticar a combinação de tempos.'],
    },
    assessment: {
      opportunityTypes: ['narrative_writing', 'error_correction', 'gap_fill'],
      evidenceRequiredForMastery: 15,
      requiredContextsForMastery: 3,
    },
    tags: ['narrative_tenses', 'b2', 'storytelling'],
    isActive: true,
  },
  {
    id: 'grammar.conditionals.third',
    version: 1,
    slug: 'third-conditional',
    title: { en: 'Third Conditional', ptBR: 'Terceiro Condicional (Situações Irreais no Passado)' },
    category: 'conditional',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.past_perfect.intro', 'grammar.conditionals.second'],
    relatedTopics: ['grammar.conditionals.second', 'grammar.conditionals.mixed_intro', 'grammar.wish_if_only'],
    communicativeUses: [
      'Especular sobre o passado alternativo',
      'Expressar arrependimento ou crítica sobre o passado',
      'Analisar situações passadas de forma hipotética',
    ],
    structures: {
      affirmative: ['If + past perfect, + would have + past participle'],
      other: ['could/might have (instead of would have for softer deduction)'],
    },
    examples: [
      { en: "If I had prepared better, I would have got the job.", ptBR: 'Se eu tivesse me preparado melhor, teria conseguido o emprego.', stage: 'guided_practice' },
      { en: "She might have succeeded if the team had supported her.", ptBR: 'Ela poderia ter tido sucesso se a equipe a tivesse apoiado.', stage: 'independent_production' },
      { en: "If they hadn't delayed the launch, the product would have been a hit.", ptBR: 'Se não tivessem atrasado o lançamento, o produto teria feito sucesso.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'If I would have known, I would have helped.', correct: 'If I had known, I would have helped.', explanationPtBR: 'Não use "would have" na cláusula com "if". Use past perfect.' },
    ],
    generationRules: {
      allowedContexts: ['análise de decisões passadas', 'retrospectiva de projetos', 'arrependimentos'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['conditional', 'third_conditional', 'b2', 'regret'],
    isActive: true,
  },
  {
    id: 'grammar.conditionals.mixed_intro',
    version: 1,
    slug: 'mixed-conditionals-intro',
    title: { en: 'Mixed Conditionals (Introduction)', ptBR: 'Condicionais Mistas (Introdução)' },
    category: 'conditional',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.conditionals.second', 'grammar.conditionals.third'],
    relatedTopics: ['grammar.conditionals.second', 'grammar.conditionals.third', 'grammar.conditionals.mixed'],
    communicativeUses: [
      'Expressar como uma condição passada afeta o presente',
      'Expressar como uma condição presente teria afetado o passado',
      'Argumentar sobre consequências entre passado e presente',
    ],
    structures: {
      other: [
        'Type 1 (past → present): If + past perfect, + would + verb base',
        'Type 2 (present → past): If + past simple, + would have + past participle',
      ],
    },
    examples: [
      { en: "If I had studied medicine, I would be a doctor now.", ptBR: 'Se eu tivesse estudado medicina, seria médico agora.', stage: 'guided_practice' },
      { en: "If she were more organized, she would have met the deadline.", ptBR: 'Se ela fosse mais organizada, teria cumprido o prazo.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: "If I hadn't studied, I would haven't this job now.", correct: "If I hadn't studied, I wouldn't have this job now.", explanationPtBR: 'No mixed conditional (passado → presente), o resultado usa "would + base".' },
    ],
    generationRules: {
      allowedContexts: ['reflexões sobre carreira', 'análise de situações hipotéticas'],
      notesForGenerator: ['Introduzir apenas após domínio sólido de 2nd e 3rd conditionals.'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['conditional', 'mixed_conditional', 'b2', 'c1'],
    isActive: true,
  },
  {
    id: 'grammar.passive.multi_tense',
    version: 1,
    slug: 'passive-multi-tense',
    title: { en: 'Passive Voice (Multiple Tenses)', ptBR: 'Voz Passiva (Múltiplos Tempos Verbais)' },
    category: 'passive',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.passive.present_simple', 'grammar.past_simple'],
    relatedTopics: ['grammar.passive.present_simple', 'grammar.passive.advanced', 'grammar.causative'],
    communicativeUses: [
      'Usar voz passiva em múltiplos tempos com precisão',
      'Escrever textos formais e acadêmicos com impessoalidade',
      'Descrever processos completos com sequência temporal passiva',
    ],
    structures: {
      affirmative: [
        'Present simple: is/are + past participle',
        'Past simple: was/were + past participle',
        'Present perfect: has/have been + past participle',
        'Future: will be + past participle',
        'Modal: must/should be + past participle',
      ],
    },
    examples: [
      { en: 'The annual report has been published this morning.', ptBR: 'O relatório anual foi publicado esta manhã.', stage: 'guided_practice' },
      { en: 'All expenses must be approved by the manager.', ptBR: 'Todas as despesas devem ser aprovadas pelo gerente.', stage: 'independent_production' },
      { en: 'The new policy was implemented last quarter and has been reviewed twice since then.', ptBR: 'A nova política foi implementada no último trimestre e foi revisada duas vezes desde então.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'The project has been complete last week.', correct: 'The project was completed last week.', explanationPtBR: 'Com "last week" (tempo específico), use was/were + particípio (past simple passivo).' },
    ],
    generationRules: {
      allowedContexts: ['relatórios', 'apresentações', 'textos corporativos', 'artigos técnicos'],
    },
    assessment: {
      opportunityTypes: ['sentence_transformation', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 15,
      requiredContextsForMastery: 3,
    },
    tags: ['passive', 'b2', 'formal_writing', 'multi_tense'],
    isActive: true,
  },
  {
    id: 'grammar.reported_speech.advanced',
    version: 1,
    slug: 'reported-speech-advanced',
    title: { en: 'Reported Speech (Advanced)', ptBR: 'Discurso Indireto (Avançado)' },
    category: 'reported_speech',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.reported_speech.basic', 'grammar.past_perfect.intro'],
    relatedTopics: ['grammar.reported_speech.basic', 'grammar.reported_speech.complex'],
    communicativeUses: [
      'Relatar perguntas, ordens e pedidos no discurso indireto',
      'Fazer reportagem e jornalismo',
      'Escrever atas e resumos formais com precisão',
    ],
    structures: {
      other: [
        'Questions: asked (if/whether for yes-no; wh-word for wh-questions) — no inversion',
        'Commands: told + object + to-infinitive (positive); told + object + not + to-infinitive (negative)',
        'Requests: asked + object + to-infinitive',
        'Suggestions: suggested + gerund or that-clause',
      ],
    },
    examples: [
      { en: '"Are you ready?" → She asked if I was ready.', ptBR: '"Você está pronto?" → Ela perguntou se eu estava pronto.', stage: 'guided_practice' },
      { en: '"Please submit the report by Friday." → He told me to submit the report by Friday.', ptBR: '"Por favor, envie o relatório até sexta." → Ele me disse para enviar o relatório até sexta.', stage: 'independent_production' },
      { en: '"Why did you miss the meeting?" → She asked me why I had missed the meeting.', ptBR: '"Por que você faltou à reunião?" → Ela me perguntou por que eu havia faltado à reunião.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'She asked where did he go.', correct: 'She asked where he had gone.', explanationPtBR: 'Em perguntas relatadas, use ordem normal de sujeito + verbo (sem inversão).' },
    ],
    generationRules: {
      allowedContexts: ['e-mails de acompanhamento', 'atas', 'reportagens', 'análise de conversas'],
    },
    assessment: {
      opportunityTypes: ['sentence_transformation', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 15,
    },
    tags: ['reported_speech', 'b2', 'questions', 'commands'],
    isActive: true,
  },
  {
    id: 'grammar.modals.past',
    version: 1,
    slug: 'modals-past',
    title: { en: 'Past Modal Verbs (could have, should have, might have)', ptBR: 'Modais no Passado (could have, should have, might have)' },
    category: 'modal',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.modals.deduction', 'grammar.past_perfect.intro'],
    relatedTopics: ['grammar.modals.deduction', 'grammar.modals.nuanced', 'grammar.conditionals.third'],
    communicativeUses: [
      'Expressar arrependimento e crítica sobre o passado',
      'Fazer deduções sobre situações passadas',
      'Expressar possibilidades não realizadas',
    ],
    structures: {
      affirmative: [
        'should have + past participle (criticism/regret)',
        "shouldn't have + past participle (it was wrong)",
        'could have + past participle (unrealized possibility)',
        "couldn't have + past participle (impossibility)",
        'must have + past participle (deduction: positive)',
        "can't have + past participle (deduction: negative)",
        'might/may have + past participle (possibility about past)',
      ],
    },
    examples: [
      { en: "You should have told me earlier — I could have helped.", ptBR: 'Você deveria ter me contado antes — eu poderia ter ajudado.', stage: 'guided_practice' },
      { en: "She can't have left already — the meeting just started.", ptBR: 'Ela não pode ter ido embora já — a reunião acabou de começar.', stage: 'independent_production' },
      { en: "They might have misunderstood the brief.", ptBR: 'Eles podem ter mal entendido o briefing.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'You should have to try harder.', correct: 'You should have tried harder.', explanationPtBR: '"Should have" é seguido diretamente do particípio passado.' },
    ],
    generationRules: {
      allowedContexts: ['retrospectivas de projetos', 'análise de decisões', 'feedback construtivo'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 15,
    },
    tags: ['modals', 'past', 'b2', 'regret', 'deduction'],
    isActive: true,
  },
  {
    id: 'grammar.wish_if_only',
    version: 1,
    slug: 'wish-if-only',
    title: { en: 'Wish and If Only', ptBR: 'Wish e If Only (Desejos e Arrependimentos)' },
    category: 'conditional',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.past_simple', 'grammar.past_perfect.intro', 'grammar.conditionals.second'],
    relatedTopics: ['grammar.conditionals.second', 'grammar.conditionals.third', 'grammar.modals.past'],
    communicativeUses: [
      'Expressar desejos irreais sobre o presente',
      'Expressar arrependimentos sobre o passado',
      'Queixar-se sobre situações que não podemos mudar',
    ],
    structures: {
      other: [
        'Present wish: wish + past simple (I wish I had more time)',
        'Past regret: wish + past perfect (I wish I had studied harder)',
        'Future wish: wish + would + base (I wish you would listen)',
        'If only: same structures, stronger emotion',
      ],
    },
    examples: [
      { en: 'I wish I could work remotely permanently.', ptBR: 'Queria poder trabalhar remotamente permanentemente.', stage: 'guided_practice' },
      { en: 'If only I had taken that opportunity when I had the chance.', ptBR: 'Se ao menos eu tivesse aproveitado aquela oportunidade quando tive a chance.', stage: 'independent_production' },
      { en: 'She wishes she had chosen a different career path.', ptBR: 'Ela deseja ter escolhido um caminho de carreira diferente.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I wish I would have more time.', correct: 'I wish I had more time.', explanationPtBR: 'Para desejos presentes, use "wish + past simple", não "wish + would have".' },
    ],
    generationRules: {
      allowedContexts: ['reflexões pessoais', 'discussões sobre vida profissional', 'análise de decisões'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['wish', 'if_only', 'b2', 'regret', 'desire'],
    isActive: true,
  },
  {
    id: 'grammar.causative',
    version: 1,
    slug: 'causative',
    title: { en: 'Causative (have/get something done)', ptBR: 'Causativa (have/get something done)' },
    category: 'verb_form',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.passive.present_simple', 'grammar.present_perfect.intro'],
    relatedTopics: ['grammar.passive.multi_tense', 'grammar.passive.advanced'],
    communicativeUses: [
      'Expressar que alguém mandou fazer algo (não fez diretamente)',
      'Falar sobre serviços contratados',
      'Linguagem profissional para delegação',
    ],
    structures: {
      affirmative: [
        'have + object + past participle (formal: I had my car repaired)',
        'get + object + past participle (informal: I got my car fixed)',
        'have/get + object + verb base (to use someone actively)',
      ],
    },
    examples: [
      { en: 'I had the contract reviewed by our legal team.', ptBR: 'Fiz o contrato ser revisado pela nossa equipe jurídica.', stage: 'guided_practice' },
      { en: 'She got her website redesigned last month.', ptBR: 'Ela mandou redesenhar seu site no mês passado.', stage: 'independent_production' },
      { en: 'We need to have the servers upgraded before the launch.', ptBR: 'Precisamos mandar atualizar os servidores antes do lançamento.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I had my car to repair.', correct: 'I had my car repaired.', explanationPtBR: 'Após "have + object", use o particípio passado, não o infinitivo.' },
    ],
    generationRules: {
      allowedContexts: ['contexto profissional', 'delegação de tarefas', 'serviços contratados'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'sentence_transformation', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['causative', 'b2', 'professional'],
    isActive: true,
  },
  {
    id: 'grammar.relative_clauses.non_defining',
    version: 1,
    slug: 'relative-clauses-non-defining',
    title: { en: 'Non-Defining Relative Clauses', ptBR: 'Orações Relativas Não Definidoras' },
    category: 'relative_clause',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.relative_clauses.defining'],
    relatedTopics: ['grammar.relative_clauses.defining', 'grammar.relative_clauses.reduced'],
    communicativeUses: [
      'Adicionar informação extra e não essencial sobre pessoas ou coisas',
      'Escrever textos mais sofisticados e informativos',
      'Usar vírgulas e pronomes relativos corretamente',
    ],
    structures: {
      other: [
        'Use commas to separate: "My manager, who has worked here for 20 years, is retiring."',
        'Cannot use "that": "My boss, which is unusual, approved everything." (use who/which)',
        'Can refer to a whole clause: "She passed the exam, which surprised everyone."',
      ],
    },
    examples: [
      { en: 'My colleague, who studied in London, speaks perfect English.', ptBR: 'Meu colega, que estudou em Londres, fala inglês perfeito.', stage: 'guided_practice' },
      { en: 'The meeting was cancelled, which disappointed everyone.', ptBR: 'A reunião foi cancelada, o que decepcionou a todos.', stage: 'independent_production' },
      { en: "The report, which took three weeks to write, was very well received.", ptBR: 'O relatório, que levou três semanas para ser escrito, foi muito bem recebido.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'My boss, that approved the plan, is brilliant.', correct: 'My boss, who approved the plan, is brilliant.', explanationPtBR: 'Em orações relativas não definidoras, use "who" para pessoas — não "that".' },
    ],
    generationRules: {
      allowedContexts: ['descrições de pessoas', 'relatórios formais', 'e-mails profissionais'],
    },
    assessment: {
      opportunityTypes: ['sentence_combination', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['relative_clauses', 'non_defining', 'b2', 'punctuation'],
    isActive: true,
  },
  {
    id: 'grammar.participle_clauses.intro',
    version: 1,
    slug: 'participle-clauses-intro',
    title: { en: 'Participle Clauses (Introduction)', ptBR: 'Orações Participiais (Introdução)' },
    category: 'verb_form',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.present_continuous', 'grammar.past_simple'],
    relatedTopics: ['grammar.participle_clauses', 'grammar.relative_clauses.reduced'],
    communicativeUses: [
      'Reduzir orações relativas para maior elegância e concisão',
      'Expressar simultaneidade ou sequência de ações de forma compacta',
      'Estilo formal escrito mais sofisticado',
    ],
    structures: {
      other: [
        'Present participle (-ing): Feeling tired, she went to bed early.',
        'Past participle (passive): Built in 1920, the building is now a museum.',
        'Perfect participle: Having finished the report, he went home.',
      ],
    },
    examples: [
      { en: 'Having reviewed all the data, the team decided to proceed.', ptBR: 'Após revisar todos os dados, a equipe decidiu prosseguir.', stage: 'guided_practice' },
      { en: 'Walking to work, I often listen to podcasts.', ptBR: 'Caminhando para o trabalho, frequentemente ouço podcasts.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'Having finished, the report was sent.', correct: 'Having finished the report, he sent it.', explanationPtBR: 'O sujeito da participle clause deve ser o mesmo da cláusula principal.' },
    ],
    generationRules: {
      allowedContexts: ['redação formal', 'artigos', 'apresentações escritas'],
      notesForGenerator: ['Introduzir gradualmente — primeiro present, depois past, depois perfect participles.'],
    },
    assessment: {
      opportunityTypes: ['sentence_combination', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['participle_clauses', 'b2', 'formal_writing'],
    isActive: true,
  },
  {
    id: 'grammar.inversion.intro',
    version: 1,
    slug: 'inversion-intro',
    title: { en: 'Inversion (Introduction)', ptBR: 'Inversão (Introdução)' },
    category: 'word_order',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.questions.basic', 'grammar.negation.basic'],
    relatedTopics: ['grammar.inversion.advanced', 'grammar.emphasis'],
    communicativeUses: [
      'Dar ênfase dramática em discursos e textos formais',
      'Usar expressões negativas no início de frase (Never, Not only...)',
      'Soar mais formal e sofisticado em inglês escrito',
    ],
    structures: {
      other: [
        'After negative adverbials: Never have I seen..., Not only did she...',
        'After restrictive expressions: Only then did I realize..., Hardly had I...',
        'After so/such: So important is this that...',
      ],
    },
    examples: [
      { en: "Never have I worked on a project this complex.", ptBR: 'Nunca trabalhei em um projeto tão complexo.', stage: 'guided_practice' },
      { en: 'Not only did she finish first, but she also helped her colleagues.', ptBR: 'Não só ela terminou primeiro, mas também ajudou seus colegas.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'Never I have seen this before.', correct: 'Never have I seen this before.', explanationPtBR: 'Após "never" no início, o auxiliar vem antes do sujeito (inversão).' },
    ],
    generationRules: {
      allowedContexts: ['discursos', 'apresentações', 'redação formal de alto nível'],
      notesForGenerator: ['Introduzir formas mais comuns primeiro: Never, Not only, Only then.'],
    },
    assessment: {
      opportunityTypes: ['sentence_transformation', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['inversion', 'b2', 'emphasis', 'formal'],
    isActive: true,
  },
  {
    id: 'grammar.discourse_markers.argumentation',
    version: 1,
    slug: 'discourse-markers-argumentation',
    title: { en: 'Discourse Markers for Argumentation', ptBR: 'Marcadores Discursivos para Argumentação' },
    category: 'discourse',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.connectors.cause_contrast'],
    relatedTopics: ['grammar.connectors.cause_contrast', 'grammar.hedging.basic', 'grammar.concession_contrast'],
    communicativeUses: [
      'Estruturar argumentos de forma clara e convincente',
      'Sinalizar a função retórica de cada parágrafo',
      'Escrever ensaios, relatórios e apresentações persuasivas',
    ],
    structures: {
      other: [
        'Addition: Furthermore, Moreover, In addition, What is more',
        'Contrast: However, On the other hand, Conversely, Nevertheless',
        'Concession: Admittedly, It is true that, While it is true that',
        'Conclusion: In conclusion, To sum up, All in all, Overall',
        'Exemplification: For instance, For example, Such as, To illustrate',
      ],
    },
    examples: [
      { en: 'Furthermore, the data suggests that remote work increases productivity.', ptBR: 'Além disso, os dados sugerem que o trabalho remoto aumenta a produtividade.', stage: 'guided_practice' },
      { en: 'Nevertheless, there are challenges that must not be ignored.', ptBR: 'No entanto, há desafios que não devem ser ignorados.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'However, she is smart but she made a mistake.', correct: 'However, she is smart. Nevertheless, she made a mistake.', explanationPtBR: '"However" e "but" expressam contraste — não combine os dois na mesma frase.' },
    ],
    generationRules: {
      allowedContexts: ['ensaios', 'relatórios', 'apresentações', 'debates'],
      notesForGenerator: ['Crucial para produção escrita formal. Integrar em missões de argumentação.'],
    },
    assessment: {
      opportunityTypes: ['gap_fill', 'free_production', 'essay_writing'],
      evidenceRequiredForMastery: 15,
    },
    tags: ['discourse_markers', 'argumentation', 'b2', 'writing'],
    isActive: true,
  },
  {
    id: 'grammar.hedging.basic',
    version: 1,
    slug: 'hedging-basic',
    title: { en: 'Hedging Language (Basic)', ptBR: 'Linguagem de Hedging — Mitigação (Básico)' },
    category: 'discourse',
    minimumExposureLevel: 'B2',
    minimumGuidedPracticeLevel: 'B2',
    minimumIndependentProductionLevel: 'B2',
    expectedMasteryLevel: 'C1',
    prerequisites: ['grammar.modals.may_might', 'grammar.modals.should'],
    relatedTopics: ['grammar.modals.may_might', 'grammar.hedging.advanced', 'grammar.discourse_markers.argumentation'],
    communicativeUses: [
      'Expressar incerteza e cautela em afirmações',
      'Mitigar afirmações para soar mais profissional e diplomático',
      'Fazer generalizações com cuidado',
      'Linguagem acadêmica e científica',
    ],
    structures: {
      other: [
        'Modal hedges: may, might, could, would',
        'Adverb hedges: possibly, probably, generally, typically, largely',
        'Verb hedges: tend to, seem to, appear to, suggest',
        'Noun phrase hedges: in some cases, to some extent, in general',
      ],
    },
    examples: [
      { en: 'This approach may not work in all situations.', ptBR: 'Esta abordagem pode não funcionar em todas as situações.', stage: 'guided_practice' },
      { en: 'The results suggest that further research is needed.', ptBR: 'Os resultados sugerem que mais pesquisa é necessária.', stage: 'independent_production' },
      { en: "There tend to be significant differences between the two groups.", ptBR: 'Tendem a existir diferenças significativas entre os dois grupos.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'The results prove completely that...', correct: 'The results suggest that... / The results strongly indicate that...', explanationPtBR: 'Em contextos acadêmicos, evite afirmações absolutas como "prove completely".' },
    ],
    generationRules: {
      allowedContexts: ['redação acadêmica', 'relatórios profissionais', 'negociações'],
    },
    assessment: {
      opportunityTypes: ['gap_fill', 'sentence_revision', 'free_production'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['hedging', 'b2', 'academic_writing', 'professional'],
    isActive: true,
  },
] as const satisfies readonly GrammarTopic[];
