import { GrammarTopic } from '../grammar-types';

export const C1_TOPICS: readonly GrammarTopic[] = [
  {
    id: 'grammar.inversion.advanced',
    version: 1,
    slug: 'inversion-advanced',
    title: { en: 'Inversion (Advanced)', ptBR: 'Inversão (Avançado)' },
    category: 'word_order',
    minimumExposureLevel: 'C1',
    minimumGuidedPracticeLevel: 'C1',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.inversion.intro'],
    relatedTopics: ['grammar.cleft_sentences', 'grammar.emphasis'],
    communicativeUses: [
      'Usar inversão em toda a amplitude de estruturas formais',
      'Dar ênfase precisa em textos acadêmicos e literários',
      'Controlar o ritmo e foco de argumentos sofisticados',
    ],
    structures: {
      other: [
        'Conditional inversion: Were I to..., Had I known..., Should you need...',
        'After so/such in formal contexts: So complex was the problem that...',
        'After comparative: No sooner..., The more..., the more...',
        'Inversion with only: Only by working harder... / Only if...',
      ],
    },
    examples: [
      { en: 'Were I to accept this offer, I would have to relocate.', ptBR: 'Se eu aceitasse esta oferta, teria que me mudar.', stage: 'guided_practice' },
      { en: 'Should you require further assistance, do not hesitate to contact us.', ptBR: 'Caso necessite de mais assistência, não hesite em nos contatar.', stage: 'independent_production' },
      { en: "Had I known about the issue earlier, I would have addressed it immediately.", ptBR: 'Se eu soubesse do problema mais cedo, teria resolvido imediatamente.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'Would I be to choose, I would...', correct: 'Were I to choose, I would...', explanationPtBR: 'A inversão condicional formal usa "Were I to", não "Would I be to".' },
    ],
    generationRules: {
      allowedContexts: ['cartas formais', 'ensaios acadêmicos', 'discursos profissionais de alto nível'],
      notesForGenerator: ['Ensinar em contextos de escrita formal e apresentações de alto impacto.'],
    },
    assessment: {
      opportunityTypes: ['sentence_transformation', 'free_production', 'essay_writing'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['inversion', 'c1', 'advanced', 'formal'],
    isActive: true,
  },
  {
    id: 'grammar.cleft_sentences',
    version: 1,
    slug: 'cleft-sentences',
    title: { en: 'Cleft Sentences', ptBR: 'Frases Clivadas (It is... that / What...)' },
    category: 'word_order',
    minimumExposureLevel: 'C1',
    minimumGuidedPracticeLevel: 'C1',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.relative_clauses.defining', 'grammar.inversion.intro'],
    relatedTopics: ['grammar.inversion.advanced', 'grammar.emphasis'],
    communicativeUses: [
      'Colocar foco e ênfase em um elemento específico da frase',
      'Contrastar informações de forma elegante',
      'Soar natural e fluente em inglês formal e escrito',
    ],
    structures: {
      other: [
        'It-cleft: It is/was + focused element + that/who + rest of clause',
        'Wh-cleft: What + clause + is/was + focused element',
        'All-cleft: All that + clause + is/was + focused element',
      ],
    },
    examples: [
      { en: "It was the quality of her presentation that impressed the board.", ptBR: 'Foi a qualidade da apresentação dela que impressionou a diretoria.', stage: 'guided_practice' },
      { en: 'What this company needs is more investment in training.', ptBR: 'O que esta empresa precisa é de mais investimento em treinamento.', stage: 'independent_production' },
      { en: 'All that matters at this point is delivering the project on time.', ptBR: 'Tudo o que importa neste momento é entregar o projeto no prazo.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'It is the quality which impressed them.', correct: 'It is the quality that impressed them.', explanationPtBR: 'Em cleft sentences com "it", use "that", não "which".' },
    ],
    generationRules: {
      allowedContexts: ['argumentação', 'discursos persuasivos', 'análises formais'],
    },
    assessment: {
      opportunityTypes: ['sentence_transformation', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['cleft_sentences', 'c1', 'emphasis', 'focus'],
    isActive: true,
  },
  {
    id: 'grammar.conditionals.mixed',
    version: 1,
    slug: 'mixed-conditionals',
    title: { en: 'Mixed Conditionals (Full)', ptBR: 'Condicionais Mistas (Completo)' },
    category: 'conditional',
    minimumExposureLevel: 'C1',
    minimumGuidedPracticeLevel: 'C1',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.conditionals.mixed_intro'],
    relatedTopics: ['grammar.conditionals.second', 'grammar.conditionals.third', 'grammar.inversion.advanced'],
    communicativeUses: [
      'Expressar relações complexas entre passado e presente com nuance completa',
      'Usar inversão em condicionais mistas (Were... / Had... / Should...)',
      'Argumentar com sofisticação sobre hipóteses e consequências',
    ],
    structures: {
      other: [
        'Past condition → Present result: If + past perfect, + would + base',
        'Present condition → Past result: If + past simple, + would have + past participle',
        'Inversion alternatives: Were/Had/Should + inversion (without "if")',
      ],
    },
    examples: [
      { en: "If I hadn't taken that risk years ago, I wouldn't be where I am today.", ptBR: 'Se eu não tivesse corrido aquele risco anos atrás, não estaria onde estou hoje.', stage: 'guided_practice' },
      { en: "Had she been more assertive, she would have got the promotion.", ptBR: 'Se ela fosse mais assertiva, teria conseguido a promoção.', stage: 'independent_production' },
      { en: "Were he more decisive, he would have made the right call at the time.", ptBR: 'Se ele fosse mais decidido, teria tomado a decisão certa na época.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'If I would have studied more, I would be smarter now.', correct: 'If I had studied more, I would be smarter now.', explanationPtBR: 'Na cláusula "if" do mixed conditional (passado → presente), use past perfect, não "would have".' },
    ],
    generationRules: {
      allowedContexts: ['análise de carreira', 'debate filosófico', 'reflexão sofisticada sobre decisões'],
    },
    assessment: {
      opportunityTypes: ['sentence_completion', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['mixed_conditionals', 'c1', 'advanced', 'hypothesis'],
    isActive: true,
  },
  {
    id: 'grammar.passive.advanced',
    version: 1,
    slug: 'passive-advanced',
    title: { en: 'Passive Voice (Advanced)', ptBR: 'Voz Passiva (Avançada)' },
    category: 'passive',
    minimumExposureLevel: 'C1',
    minimumGuidedPracticeLevel: 'C1',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.passive.multi_tense'],
    relatedTopics: ['grammar.causative', 'grammar.participle_clauses'],
    communicativeUses: [
      'Usar passiva com verbos de relato (It is said / It is believed)',
      'Passiva com infinitivos e gerúndios',
      'Passiva em estruturas complexas de nível C1+',
    ],
    structures: {
      other: [
        'Passive with reporting verbs: It is said that / He is believed to be',
        'Passive infinitive: The project is expected to finish / seems to have been delayed',
        'Passive gerund: He resents being interrupted',
        'Double object passive: She was given an award / An award was given to her',
      ],
    },
    examples: [
      { en: 'It is widely believed that remote work is here to stay.', ptBR: 'É amplamente acreditado que o trabalho remoto veio para ficar.', stage: 'guided_practice' },
      { en: 'The CEO is reported to have signed the deal this morning.', ptBR: 'Relata-se que o CEO assinou o acordo esta manhã.', stage: 'independent_production' },
      { en: 'He resents being excluded from the decision-making process.', ptBR: 'Ele ressente-se de ser excluído do processo de tomada de decisão.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'It is believed that he went abroad.', correct: 'He is believed to have gone abroad.', explanationPtBR: 'A estrutura pessoal (He is believed to...) é preferida em inglês formal.' },
    ],
    generationRules: {
      allowedContexts: ['jornalismo', 'relatórios formais', 'artigos acadêmicos'],
    },
    assessment: {
      opportunityTypes: ['sentence_transformation', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['passive', 'c1', 'advanced', 'reporting_verbs'],
    isActive: true,
  },
  {
    id: 'grammar.modals.nuanced',
    version: 1,
    slug: 'modals-nuanced',
    title: { en: 'Modal Verbs (Nuanced Use)', ptBR: 'Verbos Modais — Uso com Nuance' },
    category: 'modal',
    minimumExposureLevel: 'C1',
    minimumGuidedPracticeLevel: 'C1',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.modals.past'],
    relatedTopics: ['grammar.modals.past', 'grammar.hedging.advanced'],
    communicativeUses: [
      'Usar modais para expressar nuances finas de certeza, possibilidade e obrigação',
      'Distinguir entre registros formais e informais de modais',
      'Dominar expressões idiomáticas e semi-modais sofisticados',
    ],
    structures: {
      other: [
        'Near-modals: be bound to, be supposed to, be likely to, be about to',
        'Nuanced obligation: would rather, had better, be to (formal)',
        'Ability with nuance: was/were able to vs. could (past achievement vs. general)',
        'Modal combinations: must have been able to, should have been allowed to',
      ],
    },
    examples: [
      { en: 'The project is bound to succeed given the team involved.', ptBR: 'O projeto é destinado ao sucesso dado o time envolvido.', stage: 'guided_practice' },
      { en: 'You had better reconsider that decision before the board meeting.', ptBR: 'É melhor você reconsiderar essa decisão antes da reunião da diretoria.', stage: 'independent_production' },
      { en: "She was able to complete the task despite the lack of resources.", ptBR: 'Ela conseguiu completar a tarefa apesar da falta de recursos.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'He was able to swim when he was a child.', correct: 'He could swim when he was a child.', explanationPtBR: 'Para habilidade geral no passado, "could" é mais natural que "was able to".' },
    ],
    generationRules: {
      allowedContexts: ['contexto profissional de alto nível', 'negociações formais', 'discursos'],
    },
    assessment: {
      opportunityTypes: ['multiple_choice', 'error_correction', 'free_production'],
      evidenceRequiredForMastery: 15,
    },
    tags: ['modals', 'c1', 'nuance', 'advanced'],
    isActive: true,
  },
  {
    id: 'grammar.participle_clauses',
    version: 1,
    slug: 'participle-clauses',
    title: { en: 'Participle Clauses (Full)', ptBR: 'Orações Participiais (Completo)' },
    category: 'verb_form',
    minimumExposureLevel: 'C1',
    minimumGuidedPracticeLevel: 'C1',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.participle_clauses.intro'],
    relatedTopics: ['grammar.relative_clauses.reduced', 'grammar.passive.advanced'],
    communicativeUses: [
      'Usar all forms of participial clauses fluently in writing and speech',
      'Reduce complex sentence structures elegantly',
      'Achieve a sophisticated, natural academic and literary style',
    ],
    structures: {
      other: [
        'Absolute constructions: Weather permitting, the event will go ahead.',
        'Negative participle: Not knowing what to say, he remained silent.',
        'Passive participle: Written by an expert, the guide is trustworthy.',
        'As/Being + adjective: As a specialist, she can advise on...',
      ],
    },
    examples: [
      { en: 'Weather permitting, we will hold the event outdoors.', ptBR: 'Se o tempo permitir, realizaremos o evento ao ar livre.', stage: 'guided_practice' },
      { en: 'Not fully understanding the brief, the team made several mistakes.', ptBR: 'Não compreendendo completamente o briefing, a equipe cometeu vários erros.', stage: 'independent_production' },
      { en: 'Considered one of the best in the field, she was invited to keynote the conference.', ptBR: 'Considerada uma das melhores na área, ela foi convidada para a palestra principal da conferência.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'Not knowing the answer, the question was skipped.', correct: 'Not knowing the answer, he skipped the question.', explanationPtBR: 'O sujeito implícito da participle clause deve corresponder ao sujeito da frase principal.' },
    ],
    generationRules: {
      allowedContexts: ['escrita acadêmica', 'artigos especializados', 'ensaios de alto nível'],
    },
    assessment: {
      opportunityTypes: ['sentence_transformation', 'free_production', 'error_correction'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['participle_clauses', 'c1', 'advanced_writing'],
    isActive: true,
  },
  {
    id: 'grammar.relative_clauses.reduced',
    version: 1,
    slug: 'relative-clauses-reduced',
    title: { en: 'Reduced Relative Clauses', ptBR: 'Orações Relativas Reduzidas' },
    category: 'relative_clause',
    minimumExposureLevel: 'C1',
    minimumGuidedPracticeLevel: 'C1',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.participle_clauses.intro', 'grammar.relative_clauses.non_defining'],
    relatedTopics: ['grammar.participle_clauses', 'grammar.relative_clauses.non_defining'],
    communicativeUses: [
      'Reduzir orações relativas para um estilo mais conciso e sofisticado',
      'Soar mais natural em inglês formal escrito',
      'Aumentar densidade informacional de forma elegante',
    ],
    structures: {
      other: [
        'Active: The woman who is standing by the door → The woman standing by the door',
        'Passive: The report which was written by her → The report written by her',
        'Perfect: The man who has lived here the longest → The man having lived here the longest',
      ],
    },
    examples: [
      { en: 'The employee selected for promotion has extensive experience.', ptBR: 'O funcionário selecionado para promoção tem experiência extensa.', stage: 'guided_practice' },
      { en: 'Companies operating in multiple markets face complex challenges.', ptBR: 'Empresas operando em múltiplos mercados enfrentam desafios complexos.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'The man writing emails, he is my boss.', correct: 'The man writing emails is my boss.', explanationPtBR: 'Em relative clauses reduzidas, não repita o sujeito com pronome.' },
    ],
    generationRules: {
      allowedContexts: ['textos técnicos', 'relatórios acadêmicos', 'redação profissional avançada'],
    },
    assessment: {
      opportunityTypes: ['sentence_transformation', 'free_production'],
      evidenceRequiredForMastery: 10,
    },
    tags: ['relative_clauses', 'reduced', 'c1', 'conciseness'],
    isActive: true,
  },
  {
    id: 'grammar.reported_speech.complex',
    version: 1,
    slug: 'reported-speech-complex',
    title: { en: 'Reported Speech (Complex Structures)', ptBR: 'Discurso Indireto — Estruturas Complexas' },
    category: 'reported_speech',
    minimumExposureLevel: 'C1',
    minimumGuidedPracticeLevel: 'C1',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.reported_speech.advanced'],
    relatedTopics: ['grammar.reported_speech.advanced', 'grammar.modals.nuanced'],
    communicativeUses: [
      'Relatar discurso com expressões de atitude e epistêmicas',
      'Usar verbos de relato com valor semântico preciso',
      'Produzir relatórios e atas de alto nível de sofisticação',
    ],
    structures: {
      other: [
        'Wide range of reporting verbs: allege, insist, urge, warn, concede, imply',
        'Reporting with attitude verbs + that-clause: confessed that, admitted that, denied that',
        'Reporting verb + object + infinitive: urged him to reconsider, advised her not to rush',
        'Backshift exceptions: historic present, universal truths, unchanged situations',
      ],
    },
    examples: [
      { en: 'He insisted that the project had been mismanaged from the start.', ptBR: 'Ele insistiu que o projeto havia sido mal gerenciado desde o início.', stage: 'guided_practice' },
      { en: "She conceded that the original estimate had been too optimistic.", ptBR: 'Ela admitiu que a estimativa original havia sido otimista demais.', stage: 'independent_production' },
      { en: 'The manager urged the team not to underestimate the client\'s expectations.', ptBR: 'O gerente instou a equipe a não subestimar as expectativas do cliente.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'He said me that he was tired.', correct: 'He told me that he was tired.', explanationPtBR: '"Say" não leva objeto de pessoa direto. "Tell" requer objeto: told me, told her.' },
    ],
    generationRules: {
      allowedContexts: ['atas de reuniões de alto nível', 'jornalismo investigativo', 'análise de discursos'],
    },
    assessment: {
      opportunityTypes: ['sentence_transformation', 'free_production'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['reported_speech', 'c1', 'complex', 'reporting_verbs'],
    isActive: true,
  },
  {
    id: 'grammar.hedging.advanced',
    version: 1,
    slug: 'hedging-advanced',
    title: { en: 'Hedging Language (Advanced)', ptBR: 'Linguagem de Hedging Avançada' },
    category: 'discourse',
    minimumExposureLevel: 'C1',
    minimumGuidedPracticeLevel: 'C1',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.hedging.basic'],
    relatedTopics: ['grammar.hedging.basic', 'grammar.discourse_organization', 'grammar.modals.nuanced'],
    communicativeUses: [
      'Usar hedging de forma sofisticada em escrita acadêmica e científica',
      'Qualificar afirmações com precisão epistêmica',
      'Calibrar força ilocutória com precisão',
    ],
    structures: {
      other: [
        'Approximators: approximately, roughly, around, in the region of',
        'Shields: according to, based on, it appears that, it would seem that',
        'Plausibility shields: it is conceivable that, there is reason to believe',
        'Attribute shields: as X argues, in the view of, it has been suggested',
      ],
    },
    examples: [
      { en: "It would appear that the assumptions underlying this model require revision.", ptBR: 'Parece que as premissas subjacentes a este modelo precisam de revisão.', stage: 'guided_practice' },
      { en: 'According to current research, this approach yields promising results.', ptBR: 'De acordo com pesquisas atuais, esta abordagem produz resultados promissores.', stage: 'independent_production' },
      { en: 'There is reason to believe that the methodology may have introduced bias.', ptBR: 'Há razões para acreditar que a metodologia pode ter introduzido viés.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'The study proves that hedging is important.', correct: 'The study suggests that hedging may be important.', explanationPtBR: 'Evitar afirmações absolutas (proves, shows) em favor de hedges epistêmicos (suggests, indicates).' },
    ],
    generationRules: {
      allowedContexts: ['artigos científicos', 'relatórios de pesquisa', 'análises de mercado'],
    },
    assessment: {
      opportunityTypes: ['text_revision', 'free_production'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['hedging', 'c1', 'academic_writing', 'epistemic'],
    isActive: true,
  },
  {
    id: 'grammar.concession_contrast',
    version: 1,
    slug: 'concession-contrast',
    title: { en: 'Concession and Contrast (Advanced)', ptBR: 'Concessão e Contraste (Avançado)' },
    category: 'conjunction',
    minimumExposureLevel: 'C1',
    minimumGuidedPracticeLevel: 'C1',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.discourse_markers.argumentation'],
    relatedTopics: ['grammar.discourse_markers.argumentation', 'grammar.discourse_organization'],
    communicativeUses: [
      'Construir argumentos sofisticados com concessão estratégica',
      'Expressar nuances de contraste com precisão lexical',
      'Dominar conectores de concession em inglês formal e acadêmico',
    ],
    structures: {
      other: [
        'Concession clauses: although, even though, even if, while, whereas',
        'Concessive adverbials: nevertheless, nonetheless, even so, all the same, that said',
        'Prepositional concession: despite, in spite of, notwithstanding',
        'Advanced: be that as it may, regardless of, irrespective of',
      ],
    },
    examples: [
      { en: 'Notwithstanding the initial setbacks, the project ultimately delivered excellent results.', ptBR: 'Apesar dos contratempos iniciais, o projeto entregou excelentes resultados no final.', stage: 'guided_practice' },
      { en: "Be that as it may, we cannot ignore the data that contradicts this hypothesis.", ptBR: 'Seja como for, não podemos ignorar os dados que contradizem essa hipótese.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'Despite she worked hard, she failed.', correct: 'Despite working hard, she failed.', explanationPtBR: '"Despite" é seguido de gerúndio ou substantivo, não de sujeito + verbo.' },
    ],
    generationRules: {
      allowedContexts: ['ensaios formais', 'análises críticas', 'argumentação acadêmica'],
    },
    assessment: {
      opportunityTypes: ['gap_fill', 'free_production', 'essay_writing'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['concession', 'contrast', 'c1', 'academic_writing'],
    isActive: true,
  },
  {
    id: 'grammar.emphasis',
    version: 1,
    slug: 'emphasis',
    title: { en: 'Emphasis and Focus Structures', ptBR: 'Estruturas de Ênfase e Foco' },
    category: 'word_order',
    minimumExposureLevel: 'C1',
    minimumGuidedPracticeLevel: 'C1',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.inversion.intro', 'grammar.cleft_sentences'],
    relatedTopics: ['grammar.inversion.advanced', 'grammar.cleft_sentences'],
    communicativeUses: [
      'Colocar ênfase precisa em elementos-chave do discurso',
      'Usar toda a gama de recursos de focalização do inglês avançado',
      'Escrever e falar com impacto retórico sofisticado',
    ],
    structures: {
      other: [
        'Cleft sentences: It is X that... / What I need is...',
        'Inversion: Never have I... / Not until... / Only by...',
        'Do-emphasis (affirmative): I do agree. / She does work hard.',
        'Fronting: That report, I found it very useful. (topic fronting)',
        'Postponement: It is important that we discuss this.',
      ],
    },
    examples: [
      { en: 'What we really need is a clearer communication strategy.', ptBR: 'O que realmente precisamos é de uma estratégia de comunicação mais clara.', stage: 'guided_practice' },
      { en: 'I do believe this approach will make a significant difference.', ptBR: 'Eu realmente acredito que essa abordagem fará uma diferença significativa.', stage: 'independent_production' },
      { en: 'That proposal — I found it genuinely innovative.', ptBR: 'Aquela proposta — achei genuinamente inovadora.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'I do worked hard yesterday.', correct: 'I did work hard yesterday.', explanationPtBR: 'O "do" de ênfase no passado é "did", seguido do verbo base.' },
    ],
    generationRules: {
      allowedContexts: ['discursos persuasivos', 'debates', 'escrita de impacto'],
    },
    assessment: {
      opportunityTypes: ['sentence_transformation', 'free_production'],
      evidenceRequiredForMastery: 12,
    },
    tags: ['emphasis', 'focus', 'c1', 'rhetoric'],
    isActive: true,
  },
  {
    id: 'grammar.register_control',
    version: 1,
    slug: 'register-control',
    title: { en: 'Register Control', ptBR: 'Controle de Registro Linguístico' },
    category: 'discourse',
    minimumExposureLevel: 'C1',
    minimumGuidedPracticeLevel: 'C1',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.discourse_markers.argumentation'],
    relatedTopics: ['grammar.register_flexibility', 'grammar.hedging.advanced'],
    communicativeUses: [
      'Adaptar o registro linguístico ao contexto e audiência de forma precisa',
      'Distinguir e usar inglês formal, neutro e informal conscientemente',
      'Navegar situações profissionais com sensibilidade cultural e contextual',
    ],
    structures: {
      other: [
        'Formal markers: Latinisms (commence, endeavour, ascertain), passive constructions',
        'Informal markers: contractions, phrasal verbs, colloquialisms, hedged assertions',
        'Neutral: plain English, active voice, precise vocabulary',
        'Adjusting: lexical choice, sentence length, explicit vs. implicit meaning',
      ],
    },
    examples: [
      { en: 'Formal: I would like to enquire about the status of my application. / Informal: Any news on my application?', ptBR: 'Formal: Gostaria de perguntar sobre o status da minha candidatura. / Informal: Tem novidade sobre minha candidatura?', stage: 'guided_practice' },
      { en: "The report endeavours to ascertain the root causes of the decline.", ptBR: 'O relatório busca determinar as causas raiz do declínio.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'In a formal email: Hey! Just wanted to check...', correct: 'Dear [Name], I am writing to follow up on...', explanationPtBR: 'E-mails formais requerem saudação formal, sem contrações e vocabulário formal.' },
    ],
    generationRules: {
      allowedContexts: ['e-mails profissionais', 'apresentações de diferentes audiências', 'negociações'],
      notesForGenerator: ['Criar missões que contrastem explicitamente os registros para o mesmo conteúdo.'],
    },
    assessment: {
      opportunityTypes: ['text_rewrite', 'free_production', 'multiple_choice'],
      evidenceRequiredForMastery: 15,
      requiredContextsForMastery: 3,
    },
    tags: ['register', 'c1', 'formal', 'informal', 'professional'],
    isActive: true,
  },
  {
    id: 'grammar.discourse_organization',
    version: 1,
    slug: 'discourse-organization',
    title: { en: 'Discourse Organization', ptBR: 'Organização do Discurso' },
    category: 'discourse',
    minimumExposureLevel: 'C1',
    minimumGuidedPracticeLevel: 'C1',
    minimumIndependentProductionLevel: 'C1',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.discourse_markers.argumentation', 'grammar.connectors.cause_contrast'],
    relatedTopics: ['grammar.discourse_markers.argumentation', 'grammar.hedging.advanced'],
    communicativeUses: [
      'Estruturar textos longos e discursos com coerência e coesão totais',
      'Gerenciar referência anafórica e catafórica com precisão',
      'Construir argumentos multi-parágrafo com lógica clara',
    ],
    structures: {
      other: [
        'Macro-structure: introduction, development, conclusion with signposting',
        'Cohesion devices: pronouns, demonstratives, synonyms, ellipsis',
        'Information flow: theme-rheme, given-new structure',
        'Paragraph coherence: topic sentence, support, concluding sentence',
      ],
    },
    examples: [
      { en: "This brings us to the central question of this analysis: what drives innovation?", ptBR: 'Isso nos leva à questão central desta análise: o que impulsiona a inovação?', stage: 'guided_practice' },
      { en: 'As will be discussed in the following section, the evidence suggests a more nuanced picture.', ptBR: 'Como será discutido na seção seguinte, a evidência sugere um quadro mais matizado.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'Using the same connector repeatedly: "Also... Also... Also..."', correct: 'Varying cohesive devices: Furthermore, In addition, What is more, Additionally', explanationPtBR: 'Variar os conectivos e dispositivos coesivos para evitar repetição e monotonia.' },
    ],
    generationRules: {
      allowedContexts: ['ensaios longos', 'relatórios estruturados', 'apresentações formais'],
      notesForGenerator: ['Usar missões de escrita extensa para praticar organização macro e micro do discurso.'],
    },
    assessment: {
      opportunityTypes: ['essay_writing', 'text_analysis', 'free_production'],
      evidenceRequiredForMastery: 15,
      requiredContextsForMastery: 3,
    },
    tags: ['discourse', 'organization', 'c1', 'cohesion', 'coherence'],
    isActive: true,
  },
] as const satisfies readonly GrammarTopic[];
