import { GrammarTopic } from '../grammar-types';

export const C2_TOPICS: readonly GrammarTopic[] = [
  {
    id: 'grammar.precision',
    version: 1,
    slug: 'precision',
    title: { en: 'Precision in Language Use', ptBR: 'Precisão no Uso da Língua' },
    category: 'discourse',
    minimumExposureLevel: 'C2',
    minimumGuidedPracticeLevel: 'C2',
    minimumIndependentProductionLevel: 'C2',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.discourse_organization'],
    relatedTopics: ['grammar.register_flexibility', 'grammar.reformulation', 'grammar.implicit_meaning'],
    communicativeUses: [
      'Escolher vocabulário e estruturas que expressam significado com precisão máxima',
      'Evitar ambiguidade e imprecisão em textos complexos',
      'Calibrar cada escolha linguística com consciência total de efeito e audiência',
    ],
    structures: {
      other: [
        'Lexical precision: near-synonyms and their distinctions (affect vs effect; comprise vs constitute)',
        'Syntactic precision: choosing structures that place focus correctly',
        'Referential precision: clear antecedents, avoiding ambiguous pronouns',
        'Quantificational precision: exact vs. approximate, specific vs. generic',
      ],
    },
    examples: [
      { en: 'The policy comprises three key elements, each of which affects outcomes differently.', ptBR: 'A política compreende três elementos-chave, cada um dos quais afeta os resultados de forma diferente.', stage: 'guided_practice' },
      { en: 'These findings, rather than confirming the hypothesis, raise further questions about causality.', ptBR: 'Esses achados, em vez de confirmar a hipótese, levantam mais perguntas sobre causalidade.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'This affects on the result.', correct: 'This affects the result.', explanationPtBR: '"Affect" é transitivo — não usa preposição. "Effect" como verbo é raro e formal.' },
    ],
    generationRules: {
      allowedContexts: ['redação de alta precisão', 'revisão crítica de textos', 'comunicação profissional de nível executivo'],
      notesForGenerator: ['Priorizar tarefas de revisão e refinamento de texto, não apenas produção inicial.'],
    },
    assessment: {
      opportunityTypes: ['text_revision', 'comparative_analysis', 'free_production'],
      evidenceRequiredForMastery: 15,
      requiredContextsForMastery: 4,
    },
    tags: ['precision', 'c2', 'vocabulary', 'lexical_choice'],
    isActive: true,
  },
  {
    id: 'grammar.register_flexibility',
    version: 1,
    slug: 'register-flexibility',
    title: { en: 'Register Flexibility', ptBR: 'Flexibilidade de Registro' },
    category: 'discourse',
    minimumExposureLevel: 'C2',
    minimumGuidedPracticeLevel: 'C2',
    minimumIndependentProductionLevel: 'C2',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.register_control'],
    relatedTopics: ['grammar.idiomatic_control', 'grammar.precision'],
    communicativeUses: [
      'Transitar fluentemente entre registros distintos dentro de um mesmo texto ou discurso',
      'Misturar registros de forma intencional para efeito estilístico',
      'Adaptar instantaneamente ao interlocutor e contexto',
    ],
    structures: {
      other: [
        'Code-switching within text for rhetorical effect',
        'Mixing formal structure with accessible vocabulary for clarity',
        'Adjusting register in real-time in spoken interaction',
        'Using irony and understatement across registers',
      ],
    },
    examples: [
      { en: 'The initiative — and I use that word loosely — has yet to produce tangible results.', ptBR: 'A iniciativa — e uso esse termo com reservas — ainda não produziu resultados tangíveis.', stage: 'guided_practice' },
      { en: "In plain terms: this strategy isn't working, and we need to talk about why.", ptBR: 'Em termos simples: essa estratégia não está funcionando, e precisamos discutir o porquê.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'Mixing inappropriately: Dear Sir/Madam, Just letting you know...', correct: 'Dear Sir/Madam, I am writing to inform you... (consistent formal register)', explanationPtBR: 'Alternar registro de forma não intencional cria incoerência. Toda mudança de registro deve ser deliberada.' },
    ],
    generationRules: {
      allowedContexts: ['comunicação estratégica', 'liderança executiva', 'persuasão de alto impacto'],
    },
    assessment: {
      opportunityTypes: ['text_rewrite', 'role_play', 'free_production'],
      evidenceRequiredForMastery: 15,
      requiredContextsForMastery: 4,
    },
    tags: ['register', 'flexibility', 'c2', 'style'],
    isActive: true,
  },
  {
    id: 'grammar.idiomatic_control',
    version: 1,
    slug: 'idiomatic-control',
    title: { en: 'Idiomatic Control', ptBR: 'Controle Idiomático' },
    category: 'discourse',
    minimumExposureLevel: 'C2',
    minimumGuidedPracticeLevel: 'C2',
    minimumIndependentProductionLevel: 'C2',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.register_control', 'grammar.phrasal_verbs.common'],
    relatedTopics: ['grammar.register_flexibility', 'grammar.precision'],
    communicativeUses: [
      'Usar expressões idiomáticas, collocations e fraseologia com total naturalidade',
      'Reconhecer e produzir linguagem figurativa contextualmente apropriada',
      'Soar genuinamente nativo em interações formais e informais',
    ],
    structures: {
      other: [
        'Idioms: know the ropes, bite the bullet, get the ball rolling, hit the ground running',
        'Collocations: make a decision (not do), pay attention (not give), run a business (not do)',
        'Fixed phrases: as a matter of fact, by and large, on the whole, at face value',
        'Binomial expressions: pros and cons, black and white, sooner or later',
      ],
    },
    examples: [
      { en: 'We need someone who can hit the ground running — there is no time for a long onboarding.', ptBR: 'Precisamos de alguém que possa começar a todo vapor — não há tempo para um longo processo de integração.', stage: 'guided_practice' },
      { en: 'By and large, the team has performed beyond expectations this quarter.', ptBR: 'Em geral, a equipe teve um desempenho acima das expectativas neste trimestre.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'She made a mistake and now must bite the bullet and apologize.', correct: 'She made a mistake and must now bite the bullet and apologize.', explanationPtBR: 'Atenção à posição dos advérbios em frases idiomáticas.' },
    ],
    generationRules: {
      allowedContexts: ['conversas informais de alto nível', 'networking', 'comunicação espontânea'],
      notesForGenerator: ['Incluir collocations e phrasal verbs de frequência alta em contextos naturais.'],
    },
    assessment: {
      opportunityTypes: ['gap_fill', 'free_production', 'conversation_simulation'],
      evidenceRequiredForMastery: 20,
      requiredContextsForMastery: 4,
    },
    tags: ['idioms', 'collocations', 'c2', 'naturalness', 'fluency'],
    isActive: true,
  },
  {
    id: 'grammar.implicit_meaning',
    version: 1,
    slug: 'implicit-meaning',
    title: { en: 'Implicit Meaning and Subtext', ptBR: 'Significado Implícito e Subtexto' },
    category: 'discourse',
    minimumExposureLevel: 'C2',
    minimumGuidedPracticeLevel: 'C2',
    minimumIndependentProductionLevel: 'C2',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.precision'],
    relatedTopics: ['grammar.hedging.advanced', 'grammar.register_flexibility'],
    communicativeUses: [
      'Compreender e produzir significado além do literal em interações sofisticadas',
      'Usar implicatura, ironia e understatement com controle total',
      'Navegar situações comunicativas culturalmente sensíveis',
    ],
    structures: {
      other: [
        'Implicature: what is said vs. what is meant (Gricean maxims)',
        'Understatement: "Not the most successful project we have run."',
        'Irony and sarcasm: contextual and prosodic cues',
        'Indirect speech acts: "It is rather warm in here." (request to open window)',
        'Face-saving and politeness strategies',
      ],
    },
    examples: [
      { en: '"The presentation was... interesting." (meaning: it was not good)', ptBR: '"A apresentação foi... interessante." (significado: não foi boa)', stage: 'guided_practice' },
      { en: '"You might want to reconsider that approach." (strong implicit criticism)', ptBR: '"Você pode querer reconsiderar essa abordagem." (crítica implícita forte)', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'Missing irony in context: taking "That went well!" literally after a disaster', correct: 'Recognizing context: "That went well!" = ironic understatement after a disaster', explanationPtBR: 'Ironia requer sensibilidade ao contexto pragmático, entonação e relação entre falantes.' },
    ],
    generationRules: {
      allowedContexts: ['situações de negociação diplomática', 'conversas de alto risco', 'análise de textos literários'],
      notesForGenerator: ['Incluir análise de diálogos reais e simulações com subtexto rico.'],
    },
    assessment: {
      opportunityTypes: ['dialogue_analysis', 'role_play', 'text_interpretation'],
      evidenceRequiredForMastery: 15,
      requiredContextsForMastery: 4,
    },
    tags: ['implicit_meaning', 'pragmatics', 'c2', 'irony', 'understatement'],
    isActive: true,
  },
  {
    id: 'grammar.reformulation',
    version: 1,
    slug: 'reformulation',
    title: { en: 'Reformulation and Paraphrase', ptBR: 'Reformulação e Paráfrase' },
    category: 'discourse',
    minimumExposureLevel: 'C2',
    minimumGuidedPracticeLevel: 'C2',
    minimumIndependentProductionLevel: 'C2',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.precision', 'grammar.register_flexibility'],
    relatedTopics: ['grammar.precision', 'grammar.discourse_control'],
    communicativeUses: [
      'Reformular e clarificar em tempo real em conversações e apresentações',
      'Parafrasear fontes com precisão e integridade semântica',
      'Simplificar sem perder significado para audiências diversas',
    ],
    structures: {
      other: [
        'Clarification markers: in other words, that is to say, to put it differently, what I mean is',
        'Paraphrase strategies: synonym substitution, structural transformation, abstraction',
        'Repair sequences: what I should have said was..., let me rephrase that...',
        'Simplification: stripping jargon while retaining precision',
      ],
    },
    examples: [
      { en: "In other words, the initiative failed because it lacked clear ownership — no one felt accountable.", ptBR: 'Em outras palavras, a iniciativa falhou porque faltava propriedade clara — ninguém se sentiu responsável.', stage: 'guided_practice' },
      { en: 'Let me rephrase that: what I am suggesting is not a complete overhaul, but a targeted adjustment.', ptBR: 'Deixe-me reformular: o que estou sugerindo não é uma reformulação completa, mas um ajuste direcionado.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'Paraphrasing by only changing a few words: "The study found X" → "The research discovered X"', correct: 'True paraphrase: restructuring the sentence while preserving meaning fully', explanationPtBR: 'Parafrasear adequadamente exige reestruturação sintática e lexical profunda.' },
    ],
    generationRules: {
      allowedContexts: ['explicações técnicas para leigos', 'apresentações de diretoria', 'tradução de conceitos complexos'],
      notesForGenerator: ['Missões de simplificação de textos complexos são ideais para este tópico.'],
    },
    assessment: {
      opportunityTypes: ['text_transformation', 'explanation_task', 'free_production'],
      evidenceRequiredForMastery: 15,
      requiredContextsForMastery: 4,
    },
    tags: ['reformulation', 'paraphrase', 'c2', 'clarity'],
    isActive: true,
  },
  {
    id: 'grammar.discourse_control',
    version: 1,
    slug: 'discourse-control',
    title: { en: 'Discourse Control', ptBR: 'Controle do Discurso' },
    category: 'discourse',
    minimumExposureLevel: 'C2',
    minimumGuidedPracticeLevel: 'C2',
    minimumIndependentProductionLevel: 'C2',
    expectedMasteryLevel: 'C2',
    prerequisites: ['grammar.discourse_organization', 'grammar.discourse_markers.argumentation'],
    relatedTopics: ['grammar.discourse_organization', 'grammar.register_flexibility'],
    communicativeUses: [
      'Controlar o fluxo, direção e impacto do discurso em tempo real',
      'Gerenciar turnos, interrupções e silêncio em interações complexas',
      'Usar prosódia, pausas e ênfase oral com intenção comunicativa precisa',
    ],
    structures: {
      other: [
        'Turn-taking: "If I could just finish...", "Going back to what I said earlier..."',
        'Floor management: "That is an interesting point. What I would add is..."',
        'Topic management: "Before we move on, let us consider...", "To return to the main point..."',
        'Repair and clarification: "What I mean by that is...", "To clarify..."',
        'Meta-commentary: "And this is the key point:", "What is significant here is..."',
      ],
    },
    examples: [
      { en: "If I could just bring us back to the central issue: the data does not support this conclusion.", ptBR: 'Se me permitem retornar à questão central: os dados não sustentam essa conclusão.', stage: 'guided_practice' },
      { en: "Before we move on, I would like to flag something that I think we have overlooked.", ptBR: 'Antes de avançarmos, gostaria de destacar algo que acho que não consideramos.', stage: 'independent_production' },
    ],
    commonErrors: [
      { incorrect: 'Letting a discussion drift without redirection', correct: 'Using explicit discourse control markers: "To come back to our original question..."', explanationPtBR: 'Falantes C2 gerenciam ativamente o discurso — não deixam conversas derivar sem intenção.' },
    ],
    generationRules: {
      allowedContexts: ['reuniões de alto nível', 'debates', 'entrevistas de liderança', 'apresentações interativas'],
      notesForGenerator: ['Simular situações de alta pressão comunicativa que exigem controle ativo do discurso.'],
    },
    assessment: {
      opportunityTypes: ['role_play', 'debate_simulation', 'meeting_facilitation'],
      evidenceRequiredForMastery: 15,
      requiredContextsForMastery: 4,
    },
    tags: ['discourse_control', 'c2', 'interaction', 'spoken', 'leadership'],
    isActive: true,
  },
] as const satisfies readonly GrammarTopic[];
