export type PlannerReasonCode =
  | 'SAFE_FALLBACK_USED'
  | 'PROVISIONAL_LEVEL_CONSERVATIVE'
  | 'TOPIC_SELECTED_FOR_INTRODUCTION'
  | 'TOPIC_SELECTED_FOR_PRACTICE'
  | 'TOPIC_SELECTED_FOR_CONSOLIDATION'
  | 'TOPIC_SELECTED_FOR_MAINTENANCE'
  | 'TOPIC_SELECTED_FOR_RECOVERY'
  | 'TOPIC_BLOCKED_BY_LEVEL'
  | 'TOPIC_BLOCKED_BY_PREREQUISITE'
  | 'TOPIC_BLOCKED_BY_RECENCY'
  | 'TOPIC_BLOCKED_BY_NOVELTY_BUDGET'
  | 'TOPIC_BLOCKED_BY_RECOVERY_BUDGET'
  | 'OBJECTIVE_BLOCKED_BY_RECENCY'
  | 'SUPPORT_INCREASED_LOW_CONFIDENCE'
  | 'SUPPORT_INCREASED_RECENT_STRUGGLE'
  | 'SUPPORT_REDUCED_FOR_CONSOLIDATION'
  | 'VOCABULARY_SELECTED_FOR_REVIEW'
  | 'VOCABULARY_SKIPPED_CONTEXT_MISMATCH'
  | 'DIAGNOSTIC_MODE_ACTIVE'
  | 'CALIBRATION_MODE_ACTIVE'
  | 'MAINTENANCE_DUE'
  | 'RECOVERY_PRIORITY'
  | 'PREREQUISITE_FRAGILE'
  | 'PREREQUISITE_ABSENT'
  | 'NOVELTY_BUDGET_EXHAUSTED'
  | 'RECOVERY_BUDGET_EXHAUSTED';

export const ALL_PLANNER_REASON_CODES: readonly PlannerReasonCode[] = [
  'SAFE_FALLBACK_USED',
  'PROVISIONAL_LEVEL_CONSERVATIVE',
  'TOPIC_SELECTED_FOR_INTRODUCTION',
  'TOPIC_SELECTED_FOR_PRACTICE',
  'TOPIC_SELECTED_FOR_CONSOLIDATION',
  'TOPIC_SELECTED_FOR_MAINTENANCE',
  'TOPIC_SELECTED_FOR_RECOVERY',
  'TOPIC_BLOCKED_BY_LEVEL',
  'TOPIC_BLOCKED_BY_PREREQUISITE',
  'TOPIC_BLOCKED_BY_RECENCY',
  'TOPIC_BLOCKED_BY_NOVELTY_BUDGET',
  'TOPIC_BLOCKED_BY_RECOVERY_BUDGET',
  'OBJECTIVE_BLOCKED_BY_RECENCY',
  'SUPPORT_INCREASED_LOW_CONFIDENCE',
  'SUPPORT_INCREASED_RECENT_STRUGGLE',
  'SUPPORT_REDUCED_FOR_CONSOLIDATION',
  'VOCABULARY_SELECTED_FOR_REVIEW',
  'VOCABULARY_SKIPPED_CONTEXT_MISMATCH',
  'DIAGNOSTIC_MODE_ACTIVE',
  'CALIBRATION_MODE_ACTIVE',
  'MAINTENANCE_DUE',
  'RECOVERY_PRIORITY',
  'PREREQUISITE_FRAGILE',
  'PREREQUISITE_ABSENT',
  'NOVELTY_BUDGET_EXHAUSTED',
  'RECOVERY_BUDGET_EXHAUSTED',
] as const;
