export type MissionRejectionCode =
  | 'INVALID_JSON_SCHEMA'
  | 'MISSING_REQUIRED_FIELD'
  | 'INVALID_TITLE'
  | 'INVALID_MISSION_SETUP'
  | 'INVALID_MISSION_TASK'
  | 'INVALID_LEVEL_FIELD'
  | 'INVALID_DIFFICULTY_FIELD'
  | 'LEVEL_TOO_HIGH'
  | 'LEVEL_MISMATCH'
  | 'FORBIDDEN_GRAMMAR_REQUIRED'
  | 'PRIMARY_TOPIC_NOT_COVERED'
  | 'MISSING_REQUIRED_GRAMMAR'
  | 'GRAMMAR_TOPIC_NAME_EXPOSED'
  | 'EXPLICIT_GRAMMAR_EXERCISE'
  | 'NO_COMMUNICATIVE_PURPOSE'
  | 'SETUP_STARTS_WITH_WRITE'
  | 'MISSION_TOO_GENERIC'
  | 'MISSING_CONFLICT_OR_DECISION'
  | 'EVERYDAY_SITUATION_MISSING'
  | 'TOO_SIMILAR_TO_RECENT'
  | 'EXCESSIVE_NOVELTY'
  | 'VOCABULARY_OVERFLOW'
  | 'SUPPORT_LEVEL_MISMATCH'
  | 'FORBIDDEN_CONTEXT_FAMILY'
  | 'PREREQUISITE_TOPIC_REQUIRED';

export const ALL_MISSION_REJECTION_CODES: readonly MissionRejectionCode[] = [
  'INVALID_JSON_SCHEMA',
  'MISSING_REQUIRED_FIELD',
  'INVALID_TITLE',
  'INVALID_MISSION_SETUP',
  'INVALID_MISSION_TASK',
  'INVALID_LEVEL_FIELD',
  'INVALID_DIFFICULTY_FIELD',
  'LEVEL_TOO_HIGH',
  'LEVEL_MISMATCH',
  'FORBIDDEN_GRAMMAR_REQUIRED',
  'PRIMARY_TOPIC_NOT_COVERED',
  'MISSING_REQUIRED_GRAMMAR',
  'GRAMMAR_TOPIC_NAME_EXPOSED',
  'EXPLICIT_GRAMMAR_EXERCISE',
  'NO_COMMUNICATIVE_PURPOSE',
  'SETUP_STARTS_WITH_WRITE',
  'MISSION_TOO_GENERIC',
  'MISSING_CONFLICT_OR_DECISION',
  'EVERYDAY_SITUATION_MISSING',
  'TOO_SIMILAR_TO_RECENT',
  'EXCESSIVE_NOVELTY',
  'VOCABULARY_OVERFLOW',
  'SUPPORT_LEVEL_MISMATCH',
  'FORBIDDEN_CONTEXT_FAMILY',
  'PREREQUISITE_TOPIC_REQUIRED',
] as const;
