import type { ListeningLevelGroup } from '../listening-level-group';

/** The reconstructable content of a shared story, minus audio (Storage) and per-serve fields (answerToken, re-signed fresh every time). Matches ListeningStoryResult minus audioBase64/audioMimeType/answerToken per part. */
export interface SharedStoryContent {
  title: string;
  level: string;
  summary: string;
  parts: [SharedStoryContentPart, SharedStoryContentPart];
}

export interface SharedStoryContentPart {
  id: 1 | 2;
  text: string;
  question: {
    prompt: string;
    options: string[];
    correctOptionIndex: number;
    explanationPt: string;
  };
}

export type SharedStoryStatus = 'generating' | 'ready' | 'failed';

/** Raw row shape returned by the acquire_or_get_listening_shared_story RPC. */
export interface AcquireSharedStoryResult {
  id: string;
  status: SharedStoryStatus;
  won: boolean;
  content: SharedStoryContent | null;
  part1AudioPath: string | null;
  part2AudioPath: string | null;
  audioMimeType: string | null;
  errorMessage: string | null;
}

/** Thrown when another request already holds a live (non-expired) lock for this level_group/practice_date — caller must not call OpenAI/Azure, and should surface a simple, already-handled error to the frontend instead of a new UI state. */
export class SharedStoryGeneratingError extends Error {
  readonly code = 'LISTENING_SHARED_STORY_GENERATING';
  constructor(readonly levelGroup: ListeningLevelGroup) {
    super('A shared story for this group is already being generated by another request.');
    this.name = 'SharedStoryGeneratingError';
  }
}
